### PR TITLE
Python In-Memory Backend

### PR DESCRIPTION
**Pull request by scopatz**
This implements a RecBackend interface for that operates by storing Python versions of the tables (as pandas dataframes) in-memory.  It provides, from the Python side, the full QueryableBackend interface.

This comes complete with the notion of a "registry" that restricts table storage to only certain table names.  Additionally, a fallback backend may be provides.  Queries that are not available, for whatever reason, will instead be looked up in the fallback.

### CODE REVIEW

**Comment by scopatz** [comment]
CC @FlanFlanagan @hodger and anyone else who is interested!

**Comment by FlanFlanagan** [comment]
```
 87%] Linking CXX executable ../bin/cyclus_unit_tests
[ 92%] Built target cyclus_unit_tests
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "install.py", line 208, in <module>
    main()
  File "install.py", line 205, in main
    install_cyclus(args)
  File "install.py", line 104, in install_cyclus
    shell=(os.name == 'nt'))
  File "/home/robert/miniconda3/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j2']' returned non-zero exit status 2
```

**Comment by FlanFlanagan** [comment]
Getting the above error when trying to install this.

**Comment by scopatz** [comment]
Can you please provide the full output? This doesn't provide enough information. Thanks!

**Comment by FlanFlanagan** [comment]
Fixed by updating Cython

**Comment by scopatz** [comment]
Ok, I will make the build fail on lower version of cython.

**Comment by scopatz** [comment]
OK, it should now fail to build on versions of Cython <0.25

**Comment by FlanFlanagan** [comment]
The build fail message works and I'm getting no errors. Going to merge.

**Pull request merged**
