### PR TITLE
resource buffer popping fix

### LINKED ISSUE #1465: Python agent issue with Resource.append
Traceback (most recent call last):
  File "agents.pyx", line 945, in cyclus.agents._Agent.snapshot_inv
  File "typesystem.pyx", line 618, in cyclus.typesystem._ResBufMaterial.pop_all_res
  File "typesystem.pyx", line 588, in cyclus.typesystem._ResBufMaterial.pop_n_res
AttributeError: 'Resource' object has no attribute 'append'

This error occured at the end of a run using the in development peddler archetype. 

@scopatz

### PR DESCRIPTION
**Pull request by scopatz**
CC @FlanFlanagan Should fix #1465

### CODE REVIEW

**Comment by scopatz** [comment]
@FlanFlanagan I have updated this to address the new issue, but now I am getting a segfault.

**Comment by FlanFlanagan** [comment]
New error. And you should merge in cast_fix to your pop branch. Should fix the seg fault. 
```
Traceback (most recent call last):
  File "agents.pyx", line 946, in cyclus.agents._Agent.snapshot_inv
  File "typesystem.pyx", line 626, in cyclus.typesystem._ResBufMaterial.push_many
TypeError: Argument 'r' has incorrect type (expected cyclus.typesystem._Material, got Resource)
Exception ignored in: 'CyclusFacilityShim.SnapshotInv'
Traceback (most recent call last):
  File "agents.pyx", line 946, in cyclus.agents._Agent.snapshot_inv
  File "typesystem.pyx", line 626, in cyclus.typesystem._ResBufMaterial.push_many
TypeError: Argument 'r' has incorrect type (expected cyclus.typesystem._Material, got Resource)
Traceback (most recent call last):
  File "agents.pyx", line 946, in cyclus.agents._Agent.snapshot_inv
  File "typesystem.pyx", line 626, in cyclus.typesystem._ResBufMaterial.push_many
TypeError: Argument 'r' has incorrect type (expected cyclus.typesystem._Material, got Resource)
Exception ignored in: 'CyclusFacilityShim.SnapshotInv'
Traceback (most recent call last):
  File "agents.pyx", line 946, in cyclus.agents._Agent.snapshot_inv
  File "typesystem.pyx", line 626, in cyclus.typesystem._ResBufMaterial.push_many
TypeError: Argument 'r' has incorrect type (expected cyclus.typesystem._Material, got Resource)

```

**Comment by scopatz** [comment]
Merging in `cast_fix` and master with the current branch, I cannot reproduce the error you are seeing @FlanFlanagan. In fact, this seems to be the correct value

**Comment by scopatz** [comment]
Or rather, the simulation seems to run correctly

**Pull request merged**
