### PR TITLE
Mapintmapstrdbl

### PR DESCRIPTION
**Pull request by gidden**

### CODE REVIEW

**Comment by rwcarlsen** [comment]
This looks fine.  Just curious, does this have an immediate use case - a particular archetype?

**Comment by gidden** [comment]
Yes, I'm using it in an archetype I'm currently developing.

On Mon, Apr 6, 2015 at 2:13 PM, Robert Carlsen <notifications@github.com>
wrote:

> This looks fine. Just curious, does this have an immediate use case - a
> particular archetype?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus/pull/1114#issuecomment-90203170>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by gidden** [comment]
And figured that adding it was easy enough

On Mon, Apr 6, 2015 at 2:24 PM, Matthew Gidden <gidden@wisc.edu> wrote:

> Yes, I'm using it in an archetype I'm currently developing.
>
> On Mon, Apr 6, 2015 at 2:13 PM, Robert Carlsen <notifications@github.com>
> wrote:
>
>> This looks fine. Just curious, does this have an immediate use case - a
>> particular archetype?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cyclus/cyclus/pull/1114#issuecomment-90203170>.
>>
>
>
>
> --
> Matthew Gidden, Ph.D.
> Postdoctoral Associate, Nuclear Engineering
> The University of Wisconsin -- Madison
> Ph. 225.892.3192
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by rwcarlsen** [comment]
mac failed with "internal error" - relaunching.

**Pull request merged**
