### PR TITLE
adding c++11 make flag

### PR DESCRIPTION
**Pull request by gidden**
separating this out from #1113

### CODE REVIEW

**Comment by scopatz** [comment]
Hey @gidden - I think a new vote on the mailing list is probably called for before were merge this in.  I don't know if that was part of your plan :)

**Comment by scopatz** [comment]
And probably some discussion at tomorrows dev meeting.

**Comment by gidden** [comment]
And probably a migration to Travis..

On Tue, Apr 7, 2015 at 11:52 AM, Anthony Scopatz <notifications@github.com>
wrote:

> And probably some discussion at tomorrows dev meeting.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus/pull/1118#issuecomment-90643593>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by gidden** [comment]
moving this to 1.4 per our discussion on the topic

**Comment by gidden** [comment]
this may need similar treatment to 
https://github.com/opotowsky/cymetric/commit/92ceda0bc1cb6b44a2ac0cb28c91dbe9dbfe0ca6

**Comment by rwcarlsen** [comment]
superseded by #1216 - since we don't have travis now.

**Pull request closed without merging**
