### PR TITLE
first cut at rng print

### PR DESCRIPTION
**Pull request by FlanFlanagan**
Allows a user to print out the master scheme for a simulation. Terminates the cyclus run after the schema is printed.

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks @FlanFlanagan, this looks good. Would you be able to add this option to the Python CLI, too?

**Comment by FlanFlanagan** [comment]
I'll take a stab at it

**Comment by bam241** [comment]
@FlanFlanagan I rebase this (with a clic bouton) hope you don't mind.

**Comment by FlanFlanagan** [comment]
Rebase is fine. Thanks!

**Comment by bam241** [comment]
LGTM
this is compiling/working on my computer (MacOS - python 3.5)

I am not sure what else to test... So I let you guys ( @scopatz ) merge when you feel like it.

**Comment by scopatz** [comment]
Can you merge from develop here @FlanFlanagan? Also is there anything else that needs to be done?

**Pull request merged**
