### PR TITLE
Stub tutorial fix

### PR DESCRIPTION
**Pull request by gyutaepark**
This PR fixes issue #1468. 
- Changes to `CMakeLists.txt` may need a more thorough review to be safe @scopatz .

- There was an issue with stub_unit_tests where it fails to find the `libstub.so` file within `.local/lib/cyclus/libpath`. I tried to fix it so that the unit test could find the shared object file but could not do so. This was instead worked around by placing the *.so file along with the other cyclus so files in `.local/lib/cyclus` (this was done by editing the INSTALL_CYCLUS_MODULE macro.

- The README located in stub was also updated to reflect the changes./

### CODE REVIEW

**Comment by scopatz** [comment]
Looks good to me!

**Comment by scopatz** [comment]
Thanks @gyutaepark!

**Comment by gonuke** [comment]
Do the changes here imply that the `<path>` component of an archetype specification is not working?

**Comment by scopatz** [comment]
I think they just imply that the stubs were not installing into a sub-directory of the CYCLUS_PATH

**Comment by gyutaepark** [comment]
@gonuke @scopatz 
Sorry for the lack of clarification.
When I run `python install.py`, executables are installed in `.local/bin` and library shared objects are installed in `.local/lib/cyclus/libpath` where lib_path is specified upon calling:

`cycstub --type facility libpath:libname:tutorialfacility`

I am not sure how I could test if the path component is working but for the moment being, cycstub_unit_tests is unable to locate its library shared object. Moving the .so file from libpath to `.local/lib/cyclus/` did fix this issue.

**Pull request merged**
