### PR TITLE
Lusty Solver

### PR DESCRIPTION
**Pull request by scopatz**
This implements a simple LustySolver, based off the GreedySolver. Rather than using the heuristic of sorting based on the requester's average preference, the lusty solver sorts on the supplier with the largest quantity.

### CODE REVIEW

**Comment by scopatz** [comment]
This is dependent on #1070

**Comment by katyhuff** [comment]
I can't say I like this name.

**Comment by scopatz** [comment]
Is greedy any better?

**Comment by scopatz** [comment]
I guess this could be gluttonous, but slothful, wrathful, envious, and prideful don't really fit. I'd to hear suggestions for other names and your objections to this one.

**Comment by katyhuff** [comment]
Yes. This name conjures sexuality. In particular, the meaning relies on the
understanding that Lusty things prefer something that is largest. I think
it's quite inappropriate. That's as much of my opinion I'm really
comfortable discussing online. If you really desire to discuss it more, I'd
be happy to do so offline.

On Sun, Jan 18, 2015 at 10:21 PM, Anthony Scopatz <notifications@github.com>
wrote:

> Is greedy any better?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus/pull/1071#issuecomment-70450801>.
>



-- 
http://katyhuff.github.com

**Comment by scopatz** [comment]
Closing pending name change. Please call me. I am up now, obviously.

**Comment by katyhuff** [comment]
Hey! Thanks so much for being so responsive! Sorry to knee jerk about that!
Good luck with the PR!

On Sun, Jan 18, 2015 at 10:31 PM, Anthony Scopatz <notifications@github.com>
wrote:

> Closing pending name change. Please call me. I am up now, obviously.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus/pull/1071#issuecomment-70451390>.
>



-- 
http://katyhuff.github.com

**Pull request closed without merging**
