### PR TITLE
Portly Solver

### PR DESCRIPTION
**Pull request by scopatz**
Further discussion on the mailing list. Requires #1070

### CODE REVIEW

**Comment by katyhuff** [comment]
much better. Thanks!

On Sun, Jan 18, 2015 at 11:19 PM, Anthony Scopatz <notifications@github.com>
wrote:

> Further discussion on the mailing list. Requires #1070
> <https://github.com/cyclus/cyclus/pull/1070>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/cyclus/cyclus/pull/1072
> Commit Summary
>
>    - first insterface for specifying alternative solvers.
>    - added some tests
>    - changed to reinterpret_cast
>    - realized potential empty query error
>    - fist cut at lusty solver
>    - really fist cut at lusty solver
>    - lusty compiles
>    - added lusty solver to list
>    - portly rename
>    - removed tests
>
> File Changes
>
>    - *M* share/cyclus-flat.rng.in
>    <https://github.com/cyclus/cyclus/pull/1072/files#diff-0> (8)
>    - *M* share/cyclus.rng.in
>    <https://github.com/cyclus/cyclus/pull/1072/files#diff-1> (9)
>    - *M* src/exchange_graph.cc
>    <https://github.com/cyclus/cyclus/pull/1072/files#diff-2> (12)
>    - *M* src/exchange_graph.h
>    <https://github.com/cyclus/cyclus/pull/1072/files#diff-3> (22)
>    - *M* src/greedy_solver.cc
>    <https://github.com/cyclus/cyclus/pull/1072/files#diff-4> (4)
>    - *A* src/portly_solver.cc
>    <https://github.com/cyclus/cyclus/pull/1072/files#diff-5> (238)
>    - *A* src/portly_solver.h
>    <https://github.com/cyclus/cyclus/pull/1072/files#diff-6> (144)
>    - *M* src/sim_init.cc
>    <https://github.com/cyclus/cyclus/pull/1072/files#diff-7> (71)
>    - *M* src/sim_init.h
>    <https://github.com/cyclus/cyclus/pull/1072/files#diff-8> (1)
>    - *M* src/xml_file_loader.cc
>    <https://github.com/cyclus/cyclus/pull/1072/files#diff-9> (15)
>    - *M* tests/xml_file_loader_tests.cc
>    <https://github.com/cyclus/cyclus/pull/1072/files#diff-10> (22)
>    - *M* tests/xml_file_loader_tests.h
>    <https://github.com/cyclus/cyclus/pull/1072/files#diff-11> (4)
>
> Patch Links:
>
>    - https://github.com/cyclus/cyclus/pull/1072.patch
>    - https://github.com/cyclus/cyclus/pull/1072.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus/pull/1072>.
>



-- 
http://katyhuff.github.com

**Comment by scopatz** [comment]
np.  I figured that no one but me would want to spell out "corpulent" for the rest of time :).

**Comment by gidden** [comment]
@scopatz, can you give me an update on this PR? Do you mind if I move it to 1.4 and give it a more thorough review after this release?

**Comment by scopatz** [comment]
There did not seem to be any interest.  No one reviewed this PR. There is nothing to update until a review happens.

**Comment by gidden** [comment]
moving to 1.4

**Pull request closed without merging**
