### PR TITLE
allow in/out recipes

### PR DESCRIPTION
**Pull request by scopatz**
Needed for progress on cycamore

### CODE REVIEW

**Comment by bam241** [comment]
@scopatz I am not sure if this helps but:
 circle.yml was working for my other PR #1365 yesterday in their original version.

**Comment by scopatz** [comment]
The problem is that circle is not pushing up to docker hub. You can see this if you go to docker hub and see that cyclus/cyclus:latest was last updated 23 days ago.

**Comment by bam241** [comment]
@scopatz Does it not make sense as the last merge PR was 23days ago?

**Comment by scopatz** [comment]
Yeah, maybe. But for some reason the container isn't actually being updated.

**Comment by bam241** [comment]
Not sure to understand everything but the logic was:
-from cyclus-deps:latest rebuild cyclus/cyclus:latest on a PR (for the CI-test)
- and push the cyclus/cyclus:latest on a merge to develop

(not sure that helps...)

**Comment by bam241** [comment]
@scopatz do you want me to try this circle file on my PR ?

**Comment by bam241** [comment]
@scopatz looking at the ci log, in my case everything is installed in `/usr/local/` on your PR everything is in `/root/.local/`

**Comment by bam241** [comment]
seen you last commit make me think you are probably a step ahead of my :)

**Comment by scopatz** [comment]
Yeah, it is a PATH issue :)

**Comment by bam241** [comment]
don't you need the `pythonpath` (and the lib) too ?

**Comment by bam241** [comment]
when fixed your way seems better: it fix some of the error message we got:
```
Error removing intermediate container c5fa3d49fa06: no such id: c5fa3d49fa065bcc975115ba55663e22e193307926579245c055c65bb3951c98
```
does not appear on you build (probably the `-rm=false`)

**Comment by scopatz** [comment]
Yeah it is the `-rm=false`

**Comment by scopatz** [comment]
Great! Thanks @bam241 and @FlanFlanagan!

**Comment by bam241** [comment]
sweet ! nice work @scopatz

**Pull request merged**
