### PR TITLE
Segfaulting Fix for some high-numbered dbtyes in Python

### PR DESCRIPTION
**Pull request by scopatz**
CC @FlanFlanagan @bam241 @gonuke

### CODE REVIEW

**Comment by FlanFlanagan** [comment]
Will this need to be repeated for new Product like objects?

**Comment by FlanFlanagan** [comment]
ERROR(core  ):unsupported backend type St4pairIdSt3mapIidSt4lessIiESaIS_IKidEEEE
New error with this build attempting to run peddler

**Comment by scopatz** [comment]
Yeah, you need to use hdf5 with peddler because sqlite doesn't support the type of one of the statevars

**Comment by FlanFlanagan** [comment]
Oh right. 

Thanks!

**Comment by gwenchee** [comment]
Hey @FlanFlanagan, I also just encountered `ERROR(core ):unsupported backend type St4pairIdSt3mapIidSt4lessIiESaIS_IKidEEEE` for my conditioning archetype. What does it mean to use hdf5 with the archetype? 

Does it mean that i put this in the cli 
`cyclus test.xml -o output.h5`?

**Comment by FlanFlanagan** [comment]
yes

**Pull request merged**
