### PR TITLE
adding workflow to build docker img

### PR DESCRIPTION
**Pull request by bam241**

### CODE REVIEW

**Comment by gonuke** [comment]
Why does the nosetest fail here when testing the image but not in the normal build & test that is basically ready to merge (#1569)?

**Comment by bam241** [comment]
not sure quite yet, might be a permission issue or a path issue....

it seems that githubAction `runs` inside /github/home/... which is not the default location, I am not sure about the `build` part, some path might change, or some permission have to be fixed, or some ENV variable are missing....
probably one (or multiple) of the three...

**Comment by gonuke** [comment]
This is being superseded by #1588

**Comment by gonuke** [comment]
There is a useful update to the pattern of handling input files in the tests to help them be runnable from different locations.  Perhaps that can be lifted and abstracted into a few places in the testing.

**Comment by bam241** [comment]
this is super outdate.
closing.

**Pull request closed without merging**
