### PR TITLE
better error message for row overflow

### PR DESCRIPTION
**Pull request by gidden**
should be a simple one. @opotowsky wana take a crack? (or anyone else!)

### CODE REVIEW

**Comment by opotowsky** [comment]
I'm confused why the PR says the building and testing is good yet its pending for a specific commit.

**Comment by opotowsky** [comment]
Sorry @gidden I forgot to tag you on my last comment!

**Comment by gidden** [comment]
it now says all is well

**Comment by opotowsky** [comment]
I think I just hadn't noticed the way CI works with individual commits - it cancels then relaunches once a new one is submitted. Sorry for the delay, and thanks @gidden!

**Pull request merged**
