### PR TITLE
Integration test fixes

### PR DESCRIPTION
**Pull request by scopatz**
This fixes the integration tests on my laptop back to the point where only the symbol check gives the normal failure (and not an error).  This builds on #1262, which is also needed for me.

It is really just a minor Python2/3 bytes issue and skipping the stub tests when they assume too much about the host system (like default args on the install script, or that it has a compiler).

### CODE REVIEW

**Comment by scopatz** [comment]
OK, now that #1262 has been merged, it would be great if this could be reviewed! Thanks!

**Comment by scopatz** [comment]
ping @FlanFlanagan can you please take a look?

**Comment by scopatz** [comment]
ping anyone...

**Comment by gonuke** [comment]
I'm reviewing now - it builds fine on my system.  Any thoughts on how to force it to fail in a way that exposes the `SkipTest` addition?

**Comment by scopatz** [comment]
Thanks @gonuke!  If you remove the compiler from your PATH that should force the test to skip

**Comment by gonuke** [comment]
Removing the compiler caused other problems... 

I mangled the build_dir in the install cmd to make it fail

Thanks @scopatz

**Comment by scopatz** [comment]
Thanks @gonuke!

**Pull request merged**
