### PR TITLE
local json

### PR DESCRIPTION
**Pull request by gidden**
this is the kernel PR in a trio of dbtypes-related PRs.

it adds both the "current" version of a name-and-id-less dbtypes.js and the "old" version. Both versions are added for now because the cymetric `convert_to_py` borks on the new version, and this can help with debugging that issue. When that is complete, the `dbtypes.js.old` should be removed.

### CODE REVIEW

**Comment by gidden** [comment]
@rwcarlsen, this should be ready to go. It places the pre-v1.3 dbtypes.js file on the local file system.

**Comment by rwcarlsen** [comment]
Could we make it a json file?  Sorry to make yet another request.

**Comment by gidden** [comment]
That's going to take some nontrivial changes to the dbtypes.rst file on the
website. I'm sure someone with passable javascript chops could do it
quickly, but after mucking around for a while, I think it will take me
significantly longer. Unfortunately, I know basically no js.

On Mon, Aug 3, 2015 at 6:58 PM, Robert Carlsen <notifications@github.com>
wrote:

> Could we make it a json file? Sorry to make yet another request.
>
> On Monday, August 3, 2015, Matthew Gidden <notifications@github.com>
> wrote:
>
> > @rwcarlsen <https://github.com/rwcarlsen>, this should be ready to go.
> It
> > places the pre-v1.3 dbtypes.js file on the local file system.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cyclus/cyclus/pull/1184#issuecomment-127429931>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus/pull/1184#issuecomment-127437051>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by rwcarlsen** [comment]
I'll take a look tomorrow.

**Comment by gidden** [comment]
ok, ready to go

**Pull request merged**
