### PR TITLE
Link against libraries, don't recompile everything

### PR DESCRIPTION
**Pull request by scopatz**
This fixes the build system so that ALL of the sources aren't recompiled into the unit tests. This should speed up clean build times considerably.

CC @FlanFlanagan @cyclus/pushers

### CODE REVIEW

**Comment by scopatz** [comment]
Also, it will make the binaries smaller, which is better for packaging.

**Comment by scopatz** [comment]
On my laptop, a clean compile now takes about 5 min with 4 threads in debug mode.

**Comment by scopatz** [comment]
cycamore fix for this is available at https://github.com/cyclus/cycamore/pull/479

**Comment by scopatz** [comment]
Test seem to pass now!

**Comment by FlanFlanagan** [comment]
Merging this in.

**Comment by scopatz** [comment]
Thank you so much @FlanFlanagan!

**Pull request merged**
