### PR TITLE
V1.4.0 release update

### PR DESCRIPTION
**Pull request by Baaaaam**
I apply the modifications from develop to v1.4.0_release branch.
The goal was to exclude @hodger commit from it as it is labelled for v1.5 (and avoid a RC3)

I am not sure of what I did so here is what I did:
```
git checkout v1.4.0-release
git checkout -b v1.4.0-release_update
git merge develop
git reset --hard ef3c1db                 #move HEAD before @hodge first commit
git cherry 8485705                       #Apply @gonuke PR
git cherry b7e74db..b512935              #Apply @gonuke PR
```

### CODE REVIEW

**Comment by Baaaaam** [comment]
```
*   e50160f - (HEAD -> develop, upstream/develop, origin/develop, origin/HEAD) Merge pull request #1281 from gonuke/fix_apbi(26 hours ago) <Mouginot Baptiste>
|\
| * b512935 - Style improvements(3 days ago) <Paul P.H. Wilson>
| * c9530d1 - Fix typo that reverses meaning of error message.(4 days ago) <Paul P.H. Wilson>
| * 20af526 - Some things got lost in the rebase(4 days ago) <Paul P.H. Wilson>
| * b7e74db - Style fix(4 days ago) <Paul P.H. Wilson>
| * 8485705 - Deprecate `ProgTranslator::Context` without changing API/ABI.(4 days ago) <Paul P.H. Wilson>
* |   cd9b7f6 - Merge pull request #1254 from hodger/morecodegen(2 days ago) <Anthony Scopatz>
|\ \
| * | b452b02 - numpydoc formatting(3 days ago) <Ryan Hodge>
| * | 482ea6b - function comments(3 days ago) <Ryan Hodge>
| * | e752311 - more cleanup, added error if body cannot be found(3 days ago) <Ryan Hodge>
| * | 0ada92c - keyword argument cleanup(3 days ago) <Ryan Hodge>
| * | 18c3778 - function cleanup(3 days ago) <Ryan Hodge>
| * | 4b2d2e0 - removed old tests. Will replace(4 days ago) <Ryan Hodge>
| * | 5faef5e - removed hack fix, ALL TESTS PASS!(4 days ago) <Ryan Hodge>
| * | cb384ef - We don't segfault anymore!(4 days ago) <Ryan Hodge>
| * | 9125522 - types create sizes for their children, errors on pair(6 days ago) <Ryan Hodge>
| * | 200328c - remove unused test import(2 weeks ago) <Ryan Hodge>
| * | fc4bd01 - variable fixes(2 weeks ago) <Ryan Hodge>
| * | 08d1919 - removed wild parenthesis(2 weeks ago) <Ryan Hodge>
| * | 36ebe86 - tbtype -> tb_type(2 weeks ago) <Ryan Hodge>
| * | bb3ecb6 - All types generate!(2 weeks ago) <Ryan Hodge>
| * | 02776fd - added list, set and vector node functions + bug fixes(2 weeks ago) <Ryan Hodge>
| * | 1b0b38a - renamed reader -> body, moved to correct location in file, updated deprecated string setup and body(3 weeks ago) <Ryan Hodge>
| * | e2d93ee - First complete type is generated.(3 weeks ago) <Ryan Hodge>
| * | f820717 - added total_size var. code generates map_int_int(4 weeks ago) <Ryan Hodge>
| * | 7e96069 - PEP-8 formatting changes(4 weeks ago) <Ryan Hodge>
| * | 17a6e07 - primitive types do not have items, and thus don't need item_size(4 weeks ago) <Ryan Hodge>
| * | a438ec7 - added get_size function to setup(4 weeks ago) <Ryan Hodge>
| * | e6d31f2 - finished map body, yet to test(10 weeks ago) <Ryan Hodge>
| * | ebb0c81 - Added readers and comments, worked on adjusting system to work from inner recursive calls rather than one for loop.(3 months ago) <Ryan Hodge>
| * | 588ddda - Added some docstrings(3 months ago) <Ryan Hodge>
| * | 0916e43 - Made some PEP8 changes(3 months ago) <Ryan Hodge>
| * | 6d397c5 - Added multiple special cases for containers with strings. Tests run. Altered original string reader to become primitive string reader. This allows for more flexibility with u
sing it inside containers, and necessitates that the primitive string body have a setup, decl and teardown like any other type(4 months ago) <Ryan Hodge>
| * | cd1372d - more testing(4 months ago) <Ryan Hodge>
| * | 51b13d6 - added tests for some node structures, as well as get_setup, which works recursively correctly. woo!(4 months ago) <Ryan Hodge>
| * | 060d79f - removed semicolon from decl, fixed errors resulting from this, added block test(4 months ago) <Ryan Hodge>
| * | 0891d9c - got tests running(4 months ago) <Ryan Hodge>
| * | a653688 - syntax errors related to testing(4 months ago) <Ryan Hodge>
| * |   830bc37 - merged in from develop and resolved conflicts(4 months ago) <Ryan Hodge>
| |\ \
| * | | 1a99693 - work on the recursion(4 months ago) <Ryan Hodge>
| * | | 1490dc1 - reworked body function(5 months ago) <Ryan Hodge>
| * | | 7c52826 - Big list comprehension and making functions smart.(5 months ago) <Ryan Hodge>
| * | | dfb2af6 - more recursion(5 months ago) <Ryan Hodge>
| * | | ca2bc78 - added nothing(5 months ago) <Ryan Hodge>
| * | | f42dc32 - Began adding functions to retrieve setup, decl and body based on container and type(5 months ago) <Ryan Hodge>
| * | | aa6de9f - continued work on ast, does not compile(6 months ago) <Ryan Hodge>
| * | | 5978bb7 - implemented nodes and testsmostly(7 months ago) <Ryan Hodge>
| * | | f82e00d - testing and such(7 months ago) <Ryan Hodge>
| * | | b3682ee - halfway to making progress(7 months ago) <Ryan Hodge>
| * | | 2eabf2d - moving toward recursion slowly and painfully(8 months ago) <Ryan Hodge>
* | | |   ef3c1db - Merge pull request #1282 from Baaaaam/stubs_findCoin(4 days ago) <Anthony Scopatz>
```

**Comment by Baaaaam** [comment]
here is the log on the updated branch:
```
* babf77d - (HEAD -> v1.4.0-release_update, origin/v1.4.0-release_update) Style improvements(14 minutes ago) <Paul P.H. Wilson>
* a8ff2c2 - Fix typo that reverses meaning of error message.(14 minutes ago) <Paul P.H. Wilson>
* 16b134d - Some things got lost in the rebase(14 minutes ago) <Paul P.H. Wilson>
* 7829da3 - Deprecate `ProgTranslator::Context` without changing API/ABI.(14 minutes ago) <Paul P.H. Wilson>
*   ef3c1db - (v1.4.0-release_update_test) Merge pull request #1282 from Baaaaam/stubs_findCoin(4 days ago) <Anthony Scopatz>
```

**Comment by scopatz** [comment]
Hi @Baaaaam, I don't see why we would exclude @hodger's changes.  v1.5 is simply when we thought it might be done.  It was done before that and so probably should go in.

**Comment by scopatz** [comment]
Also, I think we need an RC3 because of @gonuke's ABI and API stability changes

**Comment by Baaaaam** [comment]
I added Hodger PR to this:
`*   e50160f - (HEAD -> v1.4.0-release_update, upstream/develop, origin/v1.4.0-release_update, origin/develop, origin/HEAD, develop) Merge pull request #1281 from gonuke/fix_apbi(2 days ago) <Mouginot Baptiste>`

**Comment by scopatz** [comment]
Thanks @Baaaaam

**Pull request merged**
