### PR TITLE
Empty API for ResBuff

### PR DESCRIPTION
**Pull request by gidden**
now on the ResBuf

related to #1156

### CODE REVIEW

**Comment by rwcarlsen** [comment]
The cpp style guide says (https://google-styleguide.googlecode.com/svn/trunk/cppguide.html#Function_Names):

> You may also use lowercase letters for other very short inlined functions. For example if a function were so cheap you would not cache the value if you were calling it in a loop, then lowercase naming would be acceptable.

**Comment by rwcarlsen** [comment]
And I'm not necessarily opposed to the renaming fundamentally, but I think it is worse to have 2 functions named also the same that do the same thing rather than have 1 function whose lack of capcase fails to match other API.  And I'd really rather not flat out rename the existing function - so I land on the side of maintaining the status quo as the lesser of 2 evils.

**Comment by gidden** [comment]
ok

On Wed, May 13, 2015 at 3:54 PM, Robert Carlsen <notifications@github.com>
wrote:

> And I'm not necessarily opposed to the renaming fundamentally, but I think
> it is worse to have 2 functions named also the same that do the same thing
> rather than have 1 function whose lack of capcase fails to match other API.
> And I'd really rather not flat out rename the existing function - so I land
> on the side of maintaining the status quo as the lesser of 2 evils.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus/pull/1157#issuecomment-101814222>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by gidden** [comment]
thanks for the discussion @rwcarlsen

**Pull request closed without merging**
