### PR TITLE
prevent double free corruption issues from cython

### PR DESCRIPTION
**Pull request by scopatz**
Should hopefully help some of the cymetric issues. @Baaaaam @FlanFlanagan

### CODE REVIEW

**Comment by Baaaaam** [comment]
How Cyclus nosetest can depend on cycamore ?

>  ERROR(core  ):No module found for path libcycamore.so

**Comment by Baaaaam** [comment]
compilation works for me on ubuntu 16.04 as well as cyclus_unit_test.

nosetest [fails](https://gist.github.com/Baaaaam/a71bb3bd8b20a4ab6786d67bad0a3eaa), but those fail are not related to your change (I have the same fail with the develop version) 

I'll will be happy to merge it, if we can understand why ci test complains about cycamore lib....

**Comment by scopatz** [comment]
Sorry @Baaaaam, I think I have a fix.  The problem was in the input file I was using that was copied from cymetric.

**Comment by scopatz** [comment]
Ok looks like it passes now.

**Comment by Baaaaam** [comment]
great ! thx @scopatz 

still have [1 nosotest failing](https://gist.github.com/Baaaaam/24fb9256fdfd579ccbadc89b10710434) on ubuntu 16.04.

as it is working on CI I'll merge!

**Comment by scopatz** [comment]
@Baaaaam That test failure is an ABI stability issue, and unrelated to this.

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
