### PR TITLE
add back old Material::comp() const for abi stability. It throws.

### LINKED ISSUE #1069: Material::comp() const removal causes ABI instability.
``const`` should be added back in.  Needed before v1.3. Nominally for @rwcarlsen 

see 25b90b46d91b4bdb0b86d49bc2c9b8fcdbfab0a6

### PR DESCRIPTION
**Pull request by rwcarlsen**
fixes #1069

### CODE REVIEW

**Comment by gidden** [comment]
I'm working on getting smbchk running in ciclus. I spent friday on and off
trying to do this and failed, today I'm trying with interactive jobs. Give
me a bit of time before merging to see if I can get the test running,
please.

On Mon, Jan 19, 2015 at 9:50 AM, Robert Carlsen <notifications@github.com>
wrote:

> fixes #1069 <https://github.com/cyclus/cyclus/issues/1069>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/cyclus/cyclus/pull/1073
> Commit Summary
>
>    - add back old Material::comp() const for abi stability. It throws.
>
> File Changes
>
>    - *M* src/material.cc
>    <https://github.com/cyclus/cyclus/pull/1073/files#diff-0> (5)
>    - *M* src/material.h
>    <https://github.com/cyclus/cyclus/pull/1073/files#diff-1> (3)
>
> Patch Links:
>
>    - https://github.com/cyclus/cyclus/pull/1073.patch
>    - https://github.com/cyclus/cyclus/pull/1073.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus/pull/1073>.
>



-- 
Matthew Gidden
Ph.D. Candidate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by jdangerx** [comment]
I don't see any problem with this. Does anyone else?

**Comment by gidden** [comment]
No problem with this at all, but our CI still doesn't actually test for ABI differences.

**Comment by scopatz** [comment]
Do you still want this to be blocked, @gidden?

**Comment by gidden** [comment]
No, I spent enough time working on the CI and still get a null result. Someone will have to spend some more dedicated time on it.

**Pull request merged**
