### PR TITLE
Fix for Hdf5Back::Schema

### PR DESCRIPTION
**Pull request by hodger**
This PR fixes a few Hdf5-related bugs that allow Schema to function properly. The main problem was reading and writing the shape attribute- this now works. 

@scopatz

### CODE REVIEW

**Comment by hodger** [comment]
Okay that failure is an issue with the tests- will fix

**Comment by scopatz** [comment]
Thanks for putting this in! Let me know when it is ready!

**Comment by hodger** [comment]
@scopatz I think it's ready!

**Comment by scopatz** [comment]
Sweet, thanks so much!!

**Pull request merged**
