### PR TITLE
Initial Python Bindings

### PR DESCRIPTION
**Pull request by scopatz**
This PR implements some initial Python bindings for Cyclus, mostly cribbed from Cymetric.  However, it does come with a host of bug fixes and a (hopefully) robust build system.  Note that the Python bindings are entirely optional and will be skipped if Cython is not installed.

It doesn't do anything fancy yet (Python archetypes, interactive run time, etc) but it does communicate with databases.  With this, cymetric should be able to be a pure-Python project (though that was not the motivation).

@FlanFlanagan @hodger and anyone else who may be interested.

### CODE REVIEW

**Comment by scopatz** [comment]
Ok it looks like the tests now pass!

**Comment by FlanFlanagan** [comment]
The code looks good to me and it builds on my machine. Anyone else checking?

**Comment by Baaaaam** [comment]
I tried to compile this using:
- ubuntu 16.04
- python 2.7.11+
- gcc version 5.4.0 20160609
- cmake version 3.5.1

python install fails:

> ############### Begin Python Install ###############
> -- Python installer:
>   PYTHON_EXECUTABLE: /usr/bin/python
>   CYCLUS_CORE_VERSION: 1.4.1-61-g38bcc2c
>   CMAKE_INSTALL_PREFIX: /home/mouginot/.local
>   CMAKE_CURRENT_BINARY_DIR: /home/mouginot/work/app/cyclus/cyclus/build
> /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'
>   warnings.warn(msg)
> running install
> running build
> running build_py
> Traceback (most recent call last):
>   File "setup.py", line 83, in <module>
>     main()
>   File "setup.py", line 79, in main
>     run_setup(core_version)
>   File "setup.py", line 67, in run_setup
>     setup(**skw)
>   File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
>     dist.run_commands()
>   File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
>     self.run_command(cmd)
>   File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
>     cmd_obj.run()
>   File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
>     self.run_command('build')
>   File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
>     cmd_obj.run()
>   File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
>     self.run_command(cmd_name)
>   File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
>     cmd_obj.run()
>   File "/usr/lib/python2.7/distutils/command/build_py.py", line 93, in run
>     self.build_packages()
>   File "/usr/lib/python2.7/distutils/command/build_py.py", line 373, in build_packages
>     self.build_module(module, module_file, package)
>   File "/usr/lib/python2.7/distutils/command/build_py.py", line 334, in build_module
>     "'package' must be a string (dot-separated), list, or tuple")
> TypeError: 'package' must be a string (dot-separated), list, or tuple
> CMake Error at cmake/SetupPyInstall.cmake:17 (message):
>   Process setup.py install failed, res_var = '1'
> Call Stack (most recent call first):
>   cmake_install.cmake:63 (include)
> 
> 
> 
> Makefile:83: recipe for target 'install' failed
> make: *** [install] Error 1
> Traceback (most recent call last):
>   File "install.py", line 208, in <module>
>     main()
>   File "install.py", line 205, in main
>     install_cyclus(args)
>   File "install.py", line 112, in install_cyclus
>     shell=(os.name == 'nt'))
>   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '[u'make', u'-j4', u'install']' returned non-zero exit status 2

**Comment by Baaaaam** [comment]
if you need more informations, just let me know

**Comment by scopatz** [comment]
This is a bug in pip / Python 2.  Fix incoming. See https://bugs.python.org/issue13943

**Comment by Baaaaam** [comment]
I recompile it, run the unit test and merge it, unless someone disagree

**Comment by scopatz** [comment]
A fix is in.

**Comment by Baaaaam** [comment]
works perfectly using python 3.5
testing 2.7 now

**Comment by scopatz** [comment]
Thanks @Baaaaam!

**Pull request merged**
