### PR TITLE
Timeseries test fix

### LINKED ISSUE #1382: Cyclus_unit_test issue
I got this error after I build cyclus and cycamore from the develop branch on github. 
I tried both cmake installation and python install.py, and they give me same error for cyclus_unit_test. 

[==========] Running 503 tests from 109 test cases.
[----------] Global test environment set-up.
[----------] 3 tests from SymbolicFunctionTests
[ RUN      ] SymbolicFunctionTests.linearfunc
[       OK ] SymbolicFunctionTests.linearfunc (0 ms)
[ RUN      ] SymbolicFunctionTests.expfunc
[       OK ] SymbolicFunctionTests.expfunc (0 ms)
[ RUN      ] SymbolicFunctionTests.piecewisefunc
[       OK ] SymbolicFunctionTests.piecewisefunc (0 ms)
[----------] 3 tests from SymbolicFunctionTests (0 ms total)

[----------] 1 test from BasicFunctionFactory
[ RUN      ] BasicFunctionFactory.constructors
[       OK ] BasicFunctionFactory.constructors (0 ms)
[----------] 1 test from BasicFunctionFactory (0 ms total)

[----------] 3 tests from MatQueryTests
[ RUN      ] MatQueryTests.MassAndMoles
[       OK ] MatQueryTests.MassAndMoles (7 ms)
[ RUN      ] MatQueryTests.AlmostEq
[       OK ] MatQueryTests.AlmostEq (0 ms)
[ RUN      ] MatQueryTests.Amount
[       OK ] MatQueryTests.Amount (0 ms)
[----------] 3 tests from MatQueryTests (7 ms total)

[----------] 2 tests from MaterialMatQueryTest
[ RUN      ] MaterialMatQueryTest.ExtractCompleteInexactComp
[       OK ] MaterialMatQueryTest.ExtractCompleteInexactComp (0 ms)
[ RUN      ] MaterialMatQueryTest.ExtractDiffComp
[       OK ] MaterialMatQueryTest.ExtractDiffComp (0 ms)
[----------] 2 tests from MaterialMatQueryTest (0 ms total)

[----------] 2 tests from BuildingManagerTests
[ RUN      ] BuildingManagerTests.problem
Coin0506I Presolve 1 (0) rows, 2 (0) columns and 2 (0) elements
Clp0006I 0  Obj 0 Primal inf 1.2512499 (1)
Clp0006I 1  Obj 1001
Clp0000I Optimal - objective value 1001
Clp0032I Optimal objective 1001 - 1 iterations time 0.002
 Warning: Use of OsiCbc is deprecated.
 To enjoy the full performance of Cbc, use the CbcSolver interface.
Clp0000I Optimal - objective value 1001
Cbc0045I Heuristic rounding took 0 seconds (no good)
Clp0000I Optimal - objective value 1001
Cbc0046I Root node pass 1, 1 rows, 0 total tight cuts  -  objective 1001
Clp0006I 0  Obj 1001 Primal inf 1.4974998 (2)
Clp0006I 1  Obj 1001
Clp0000I Optimal - objective value 1001
Clp0000I Optimal - objective value 1001
Cbc0046I Root node pass 2, 2 rows, 1 total tight cuts  -  objective 1001
Clp0006I 0  Obj 1001 Primal inf 0.2487499 (1)
Clp0006I 1  Obj 1200
Clp0000I Optimal - objective value 1200
Cbc0046I Root node pass 3, 3 rows, 2 total tight cuts  -  objective 1200
Clp0006I 0  Obj 1200 Primal inf 0.49666089 (2)
Clp0006I 1  Obj 1200
Clp0000I Optimal - objective value 1200
Clp0000I Optimal - objective value 1200
Cbc0046I Root node pass 4, 3 rows, 2 total tight cuts  -  objective 1200
Clp0000I Optimal - objective value 1200
Cbc0012I Integer solution of 1200 found by rounding after 3 iterations and 0 nodes (0.00 seconds)
Cbc0031I 2 added rows had average density of 2
Cbc0013I At root node, 2 cuts changed objective from 1001 to 1200 in 4 passes
Cbc0014I Cut generator 0 (Probing) - 0 row cuts average 0.0 elements, 1 column cuts (1 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 1 (Gomory) - 3 row cuts average 2.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 2 (Knapsack) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 3 (Clique) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 4 (FlowCover) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 5 (MixedIntegerRounding2) - 2 row cuts average 2.0 elements, 0 column cuts (2 active)  in 0.000 seconds - new frequency is -100
Cbc0001I Search completed - best objective 1200, took 3 iterations and 0 nodes (0.00 seconds)
Cbc0035I Maximum depth 0, 0 variables fixed on reduced cost
Clp0000I Optimal - objective value 1200
Clp0006I 0  Obj 1001 Primal inf 0.2487499 (1)
Clp0006I 1  Obj 1200
Clp0000I Optimal - objective value 1200
[       OK ] BuildingManagerTests.problem (2 ms)
[ RUN      ] BuildingManagerTests.emptyorder
[       OK ] BuildingManagerTests.emptyorder (0 ms)
[----------] 2 tests from BuildingManagerTests (2 ms total)

[----------] 2 tests from CommodRecCtx
[ RUN      ] CommodRecCtx.All
[       OK ] CommodRecCtx.All (0 ms)
[ RUN      ] CommodRecCtx.DuplicateOutcommod
[       OK ] CommodRecCtx.DuplicateOutcommod (0 ms)
[----------] 2 tests from CommodRecCtx (0 ms total)

[----------] 4 tests from MatlSellPolicyTests
[ RUN      ] MatlSellPolicyTests.Init
Experimental Warning: MatlSellPolicy is experimental and its API may be subject to change
[       OK ] MatlSellPolicyTests.Init (18 ms)
[ RUN      ] MatlSellPolicyTests.StartStop
Experimental Warning: MatlSellPolicy is experimental and its API may be subject to change
[       OK ] MatlSellPolicyTests.StartStop (14 ms)
[ RUN      ] MatlSellPolicyTests.Bids
Experimental Warning: MatlSellPolicy is experimental and its API may be subject to change
[       OK ] MatlSellPolicyTests.Bids (15 ms)
[ RUN      ] MatlSellPolicyTests.Trades
Experimental Warning: MatlSellPolicy is experimental and its API may be subject to change
[       OK ] MatlSellPolicyTests.Trades (14 ms)
[----------] 4 tests from MatlSellPolicyTests (63 ms total)

[----------] 3 tests from MatlBuyPolicyTests
[ RUN      ] MatlBuyPolicyTests.Init
Experimental Warning: MatlBuyPolicy is experimental and its API may be subject to change
[       OK ] MatlBuyPolicyTests.Init (15 ms)
[ RUN      ] MatlBuyPolicyTests.StartStop
Experimental Warning: MatlBuyPolicy is experimental and its API may be subject to change
[       OK ] MatlBuyPolicyTests.StartStop (14 ms)
[ RUN      ] MatlBuyPolicyTests.Reqs
Experimental Warning: MatlBuyPolicy is experimental and its API may be subject to change
[       OK ] MatlBuyPolicyTests.Reqs (16 ms)
[----------] 3 tests from MatlBuyPolicyTests (46 ms total)

[----------] 4 tests from TimeSeriesTests
[ RUN      ] TimeSeriesTests.Power
Segmentation fault (core dumped)

### PR DESCRIPTION
**Pull request by scopatz**
This should fix #1382.  CC @orpheus92 @FlanFlanagan @bam241

### CODE REVIEW

**Comment by scopatz** [comment]
ping!

**Comment by katyhuff** [comment]
I was able to replicate #1382. Then, rebuilding with this fix succeeded in running all the tests. The tests pass, HOWEVER, a bunch of the following ignored exception warnings were thrown amongst the tests just a snippet appears in the details below, but the full test output is chock full of them:

<details>
<summary>ignored py_del_agent stuff</summary>
[----------] 2 tests from RegionClassTests
[ RUN      ] RegionClassTests.TickIter
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] RegionClassTests.TickIter (48 ms)
[ RUN      ] RegionClassTests.TockIter
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] RegionClassTests.TockIter (50 ms)
[----------] 2 tests from RegionClassTests (101 ms total)

[----------] 7 tests from InfileTreeTest
[ RUN      ] InfileTreeTest.constructor
[       OK ] InfileTreeTest.constructor (0 ms)
[ RUN      ] InfileTreeTest.top_level_queries
[       OK ] InfileTreeTest.top_level_queries (0 ms)
[ RUN      ] InfileTreeTest.top_level_throws
[       OK ] InfileTreeTest.top_level_throws (0 ms)
[ RUN      ] InfileTreeTest.null_query
[       OK ] InfileTreeTest.null_query (0 ms)
[ RUN      ] InfileTreeTest.mid_level_queries
[       OK ] InfileTreeTest.mid_level_queries (0 ms)
[ RUN      ] InfileTreeTest.low_level_queries
[       OK ] InfileTreeTest.low_level_queries (1 ms)
[ RUN      ] InfileTreeTest.optional_queries
[       OK ] InfileTreeTest.optional_queries (0 ms)
[----------] 7 tests from InfileTreeTest (1 ms total)

[----------] 3 tests from RequestPortfolioTests
[ RUN      ] RequestPortfolioTests.ReqAdd
[       OK ] RequestPortfolioTests.ReqAdd (47 ms)
[ RUN      ] RequestPortfolioTests.CapAdd
[       OK ] RequestPortfolioTests.CapAdd (66 ms)
[ RUN      ] RequestPortfolioTests.Sets
[       OK ] RequestPortfolioTests.Sets (41 ms)
[----------] 3 tests from RequestPortfolioTests (155 ms total)

[----------] 2 tests from ConditionerTests
[ RUN      ] ConditionerTests.AvgPref
[       OK ] ConditionerTests.AvgPref (0 ms)
[ RUN      ] ConditionerTests.Conditioning
[       OK ] ConditionerTests.Conditioning (0 ms)
[----------] 2 tests from ConditionerTests (1 ms total)

[----------] 5 tests from NullInstTest
[ RUN      ] NullInstTest.clone
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullInstTest.clone (48 ms)
[ RUN      ] NullInstTest.InitialState
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullInstTest.InitialState (35 ms)
[ RUN      ] NullInstTest.Print
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullInstTest.Print (45 ms)
[ RUN      ] NullInstTest.Tick
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullInstTest.Tick (55 ms)
[ RUN      ] NullInstTest.Tock
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullInstTest.Tock (51 ms)
[----------] 5 tests from NullInstTest (263 ms total)

[----------] 6 tests from NullRegionTest
[ RUN      ] NullRegionTest.clone
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullRegionTest.clone (40 ms)
[ RUN      ] NullRegionTest.InitialState
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullRegionTest.InitialState (53 ms)
[ RUN      ] NullRegionTest.Print
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullRegionTest.Print (51 ms)
[ RUN      ] NullRegionTest.ReceiveMessage
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullRegionTest.ReceiveMessage (44 ms)
[ RUN      ] NullRegionTest.Tick
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullRegionTest.Tick (49 ms)
[ RUN      ] NullRegionTest.Tock
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullRegionTest.Tock (49 ms)
[----------] 6 tests from NullRegionTest (306 ms total)

[----------] 6 tests from SinkTest
[ RUN      ] SinkTest.clone
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SinkTest.clone (49 ms)
[ RUN      ] SinkTest.InitialState
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SinkTest.InitialState (52 ms)
[ RUN      ] SinkTest.Print
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SinkTest.Print (46 ms)
[ RUN      ] SinkTest.ReceiveMessage
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SinkTest.ReceiveMessage (48 ms)
[ RUN      ] SinkTest.Tick
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SinkTest.Tick (42 ms)
[ RUN      ] SinkTest.Tock
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SinkTest.Tock (57 ms)
[----------] 6 tests from SinkTest (314 ms total)

[----------] 6 tests from SourceTest
[ RUN      ] SourceTest.clone
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SourceTest.clone (56 ms)
[ RUN      ] SourceTest.InitialState
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SourceTest.InitialState (55 ms)
[ RUN      ] SourceTest.Print
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SourceTest.Print (39 ms)
[ RUN      ] SourceTest.ReceiveMessage
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SourceTest.ReceiveMessage (34 ms)
[ RUN      ] SourceTest.Tick
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SourceTest.Tick (53 ms)
[ RUN      ] SourceTest.Tock
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SourceTest.Tock (47 ms)
[----------] 6 tests from SourceTest (312 ms total)

[----------] 1 test from KFacilityTest
[ RUN      ] KFacilityTest.clone
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] KFacilityTest.clone (51 ms)
[----------] 1 test from KFacilityTest (51 ms total)

[----------] 3 tests from NullInst/InstitutionTests
[ RUN      ] NullInst/InstitutionTests.Tick/0
[       OK ] NullInst/InstitutionTests.Tick/0 (49 ms)
[ RUN      ] NullInst/InstitutionTests.Tock/0
[       OK ] NullInst/InstitutionTests.Tock/0 (60 ms)
[ RUN      ] NullInst/InstitutionTests.Entity/0
[       OK ] NullInst/InstitutionTests.Entity/0 (47 ms)
[----------] 3 tests from NullInst/InstitutionTests (166 ms total)

[----------] 3 tests from NullRegion/RegionTests
[ RUN      ] NullRegion/RegionTests.Print/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullRegion/RegionTests.Print/0 (44 ms)
[ RUN      ] NullRegion/RegionTests.IsRegion/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullRegion/RegionTests.IsRegion/0 (46 ms)
[ RUN      ] NullRegion/RegionTests.Entity/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullRegion/RegionTests.Entity/0 (44 ms)
[----------] 3 tests from NullRegion/RegionTests (148 ms total)

[----------] 2 tests from SinkFac/FacilityTests
[ RUN      ] SinkFac/FacilityTests.Construct/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SinkFac/FacilityTests.Construct/0 (35 ms)
[ RUN      ] SinkFac/FacilityTests.Entity/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SinkFac/FacilityTests.Entity/0 (53 ms)
[----------] 2 tests from SinkFac/FacilityTests (91 ms total)

[----------] 2 tests from SourceFac/FacilityTests
[ RUN      ] SourceFac/FacilityTests.Construct/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SourceFac/FacilityTests.Construct/0 (52 ms)
[ RUN      ] SourceFac/FacilityTests.Entity/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SourceFac/FacilityTests.Entity/0 (47 ms)
[----------] 2 tests from SourceFac/FacilityTests (108 ms total)

[----------] 2 tests from KFac/FacilityTests
[ RUN      ] KFac/FacilityTests.Construct/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] KFac/FacilityTests.Construct/0 (54 ms)
[ RUN      ] KFac/FacilityTests.Entity/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] KFac/FacilityTests.Entity/0 (50 ms)
[----------] 2 tests from KFac/FacilityTests (109 ms total)

[----------] 8 tests from NullInst/AgentTests
[ RUN      ] NullInst/AgentTests.Clone/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullInst/AgentTests.Clone/0 (55 ms)
[ RUN      ] NullInst/AgentTests.Print/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullInst/AgentTests.Print/0 (46 ms)
[ RUN      ] NullInst/AgentTests.Schema/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullInst/AgentTests.Schema/0 (41 ms)
[ RUN      ] NullInst/AgentTests.GetAgentType/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullInst/AgentTests.GetAgentType/0 (42 ms)
[ RUN      ] NullInst/AgentTests.Annotations/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullInst/AgentTests.Annotations/0 (56 ms)
[ RUN      ] NullInst/AgentTests.Annotations_Name/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullInst/AgentTests.Annotations_Name/0 (50 ms)
[ RUN      ] NullInst/AgentTests.Annotations_Parents/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullInst/AgentTests.Annotations_Parents/0 (42 ms)
[ RUN      ] NullInst/AgentTests.Annotations_AllParents/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullInst/AgentTests.Annotations_AllParents/0 (56 ms)
[----------] 8 tests from NullInst/AgentTests (424 ms total)

[----------] 8 tests from NullRegion/AgentTests
[ RUN      ] NullRegion/AgentTests.Clone/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullRegion/AgentTests.Clone/0 (54 ms)
[ RUN      ] NullRegion/AgentTests.Print/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullRegion/AgentTests.Print/0 (54 ms)
[ RUN      ] NullRegion/AgentTests.Schema/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullRegion/AgentTests.Schema/0 (49 ms)
[ RUN      ] NullRegion/AgentTests.GetAgentType/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullRegion/AgentTests.GetAgentType/0 (48 ms)
[ RUN      ] NullRegion/AgentTests.Annotations/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullRegion/AgentTests.Annotations/0 (50 ms)
[ RUN      ] NullRegion/AgentTests.Annotations_Name/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullRegion/AgentTests.Annotations_Name/0 (46 ms)
[ RUN      ] NullRegion/AgentTests.Annotations_Parents/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullRegion/AgentTests.Annotations_Parents/0 (61 ms)
[ RUN      ] NullRegion/AgentTests.Annotations_AllParents/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] NullRegion/AgentTests.Annotations_AllParents/0 (60 ms)
[----------] 8 tests from NullRegion/AgentTests (450 ms total)

[----------] 8 tests from SinkFac/AgentTests
[ RUN      ] SinkFac/AgentTests.Clone/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SinkFac/AgentTests.Clone/0 (56 ms)
[ RUN      ] SinkFac/AgentTests.Print/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SinkFac/AgentTests.Print/0 (34 ms)
[ RUN      ] SinkFac/AgentTests.Schema/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SinkFac/AgentTests.Schema/0 (45 ms)
[ RUN      ] SinkFac/AgentTests.GetAgentType/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SinkFac/AgentTests.GetAgentType/0 (51 ms)
[ RUN      ] SinkFac/AgentTests.Annotations/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SinkFac/AgentTests.Annotations/0 (58 ms)
[ RUN      ] SinkFac/AgentTests.Annotations_Name/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SinkFac/AgentTests.Annotations_Name/0 (50 ms)
[ RUN      ] SinkFac/AgentTests.Annotations_Parents/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SinkFac/AgentTests.Annotations_Parents/0 (45 ms)
[ RUN      ] SinkFac/AgentTests.Annotations_AllParents/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SinkFac/AgentTests.Annotations_AllParents/0 (43 ms)
[----------] 8 tests from SinkFac/AgentTests (410 ms total)

[----------] 8 tests from SourceFac/AgentTests
[ RUN      ] SourceFac/AgentTests.Clone/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SourceFac/AgentTests.Clone/0 (40 ms)
[ RUN      ] SourceFac/AgentTests.Print/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SourceFac/AgentTests.Print/0 (54 ms)
[ RUN      ] SourceFac/AgentTests.Schema/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SourceFac/AgentTests.Schema/0 (46 ms)
[ RUN      ] SourceFac/AgentTests.GetAgentType/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SourceFac/AgentTests.GetAgentType/0 (46 ms)
[ RUN      ] SourceFac/AgentTests.Annotations/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SourceFac/AgentTests.Annotations/0 (49 ms)
[ RUN      ] SourceFac/AgentTests.Annotations_Name/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SourceFac/AgentTests.Annotations_Name/0 (50 ms)
[ RUN      ] SourceFac/AgentTests.Annotations_Parents/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SourceFac/AgentTests.Annotations_Parents/0 (47 ms)
[ RUN      ] SourceFac/AgentTests.Annotations_AllParents/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] SourceFac/AgentTests.Annotations_AllParents/0 (50 ms)
[----------] 8 tests from SourceFac/AgentTests (417 ms total)

[----------] 8 tests from KFac/AgentTests
[ RUN      ] KFac/AgentTests.Clone/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] KFac/AgentTests.Clone/0 (52 ms)
[ RUN      ] KFac/AgentTests.Print/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] KFac/AgentTests.Print/0 (56 ms)
[ RUN      ] KFac/AgentTests.Schema/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] KFac/AgentTests.Schema/0 (42 ms)
[ RUN      ] KFac/AgentTests.GetAgentType/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] KFac/AgentTests.GetAgentType/0 (36 ms)
[ RUN      ] KFac/AgentTests.Annotations/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] KFac/AgentTests.Annotations/0 (45 ms)
[ RUN      ] KFac/AgentTests.Annotations_Name/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] KFac/AgentTests.Annotations_Name/0 (58 ms)
[ RUN      ] KFac/AgentTests.Annotations_Parents/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] KFac/AgentTests.Annotations_Parents/0 (51 ms)
[ RUN      ] KFac/AgentTests.Annotations_AllParents/0
Exception ignored in: 'pymodule.py_del_agent'
NameError: name 'cyclib' is not defined
[       OK ] KFac/AgentTests.Annotations_AllParents/0 (59 ms)
[----------] 8 tests from KFac/AgentTests (426 ms total)

[----------] Global test environment tear-down
[==========] 503 tests from 109 test cases ran. (26697 ms total)
[  PASSED  ] 503 tests.
</details>

I didn't see those before (when I built cyclus fresh last week), and it seems related to https://github.com/cyclus/cyclus/issues/1366. I'm on a fresh ubuntu 16.04 vm using python 3.5.

I also have pressed the update branch button and am waiting to see what circleci says...

**Comment by katyhuff** [comment]
This looks good, makes the segfaulting tests pass now for me, as mentioned, and I don't *think* it's at all related to the issue in #1366 (which was, clearly, present before this pull request for other people) . So, I'm going to merge it. Thanks @scopatz !

**Comment by scopatz** [comment]
Thanks @katyhuff!

**Pull request merged**
