### PR TITLE
WIP: Hdf5 code generation, VLDataset, WriteToBuf, FillBuf

### PR DESCRIPTION
**Pull request by hodger**
I've implemented generation for three more Hdf5 backend functions. Currently, I am seeing all Hdf5 tests passing. I still need to finish support for nested container types before this is merged in. 

Strangely, I seem to be getting a segfault on the bugfix tests- we'll have to see if that shows up on the CI build.

@scopatz

### CODE REVIEW

**Comment by scopatz** [comment]
@hodger - let us know when this is good for another look

**Comment by hodger** [comment]
@scopatz Looking at CI, it seems like the unit tests are still segfaulting at Lone Trader, even after I merged in the recent fixes from develop. Any idea why that might be?

**Comment by scopatz** [comment]
Hmm, could you try merging from develop again?  @FlanFlanagan merged in the pywrap branch which I think may have more fixes (or at least works!). Thanks!

**Comment by hodger** [comment]
Looks like Lone Trader still isn't passing. It's strange, since I was seeing all unit tests passing on your branch from #1330.

**Comment by scopatz** [comment]
Software is the worst.  Do the tests pass locally for you? It is possible that this is new segfault in the same test. Note that the Python tests seem to pass OK, maybe.

**Comment by hodger** [comment]
I get a segfault after Lone Trader in the same place that the CI does, unfortunately.

**Comment by scopatz** [comment]
Weird, so do I.  But If I run the Lone test by itself (alone?) it runs just fine.

**Comment by scopatz** [comment]
Ok, the segfault is in importing numpy when we import cyclus.events. The backtrack is 320 calls deep, so I won't include it here.

**Comment by scopatz** [comment]
Ok this problem is happening on develop for me too.

**Comment by scopatz** [comment]
Yeah, this is totally different. I am investigating now.

**Comment by scopatz** [comment]
I think it is this issue: numpy/numpy#7595

**Comment by scopatz** [comment]
You might want to merge in the other PR with the fix

**Comment by FlanFlanagan** [comment]
I've tested this with the numpy fix and cyclus unit tests all pass for me. Is this good to go in @hodger ?

**Comment by hodger** [comment]
I believe that all the generated code is correct at this point. I'll probably need to tweak some of this as we finish generating the other hdf5_back functions and begin adding more complicated types. It's probably safe to put this in though since we're currently trying to generate what was originally there.

**Comment by scopatz** [comment]
Thanks @hodger!

**Pull request merged**
