### PR TITLE
startup python in mocksim

### PR DESCRIPTION
**Pull request by scopatz**
This may address #1372 @mbmcgarry @Baaaaam

### CODE REVIEW

**Comment by scopatz** [comment]
Ok, the current version fixes the segfaults for me locally.  @mbmcgarry @Baaaaam @FlanFlanagan @hodger

**Comment by scopatz** [comment]
It also adds some test and compilation cleanup, too.

**Comment by hodger** [comment]
@scopatz this fixed the unit test segfaults for me on Ubuntu.

**Comment by scopatz** [comment]
Sweet! Well, feel free to merge then, since it represents some progress :)

**Pull request merged**
