### PR TITLE
Fixed spelling mistakes

### PR DESCRIPTION
**Pull request by gyutaepark**
Fixes minor spelling mistakes and a missing quotation mark on `INSTALL.rst`

### CODE REVIEW

**Comment by scopatz** [comment]
LGTM! Thanks!

**Comment by gyutaepark** [comment]
Hmm how do I fix the issue with ci/circleci?

**Comment by katyhuff** [comment]
circleci is failing for reasons other than your PR. Just wait for now and it will be fixed soon.

**Comment by scopatz** [comment]
Sorry @gyutaepark - I have been working on updating and improving the CI. But there is this weird initial build bug I thought went away and it didn't.

**Comment by scopatz** [comment]
Hi @gyutaepark @katyhuff, #1399 needs to go in before this will be pass.  Please feel free to review and sorry about the bother!

**Comment by scopatz** [comment]
Hi @gyutaepark - can you please merge from develop? Thanks!

**Comment by gyutaepark** [comment]
Sorry for the delay!
I've fetched and merged so this PR should be ready for merging.

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
