### PR TITLE
Mac doc

### PR DESCRIPTION
**Pull request by mbmcgarry**
Added documentation for installing Cyclus from source on Mac.

### CODE REVIEW

**Comment by gidden** [comment]
Hi folks, could any one of @katyhuff @deniadjokic or vincent take a look at this, if possible?

**Comment by gidden** [comment]
And now, calling @vcloitre =)

**Comment by vcloitre** [comment]
These instructions worked for my installation yesterday :)
The only difference is I used hdf5 v.1.8.14 instead of v.1.8.13

**Comment by gidden** [comment]
@mbmcgarry and @vcloitre, are you both seeing HDF5 test failures?

**Comment by vcloitre** [comment]
Yes I had HDF5 test failures indeed.

**Comment by mbmcgarry** [comment]
Yes.  I see HDF5 failures when running cyclus_unit_tests.  As well as cryptic ‘developer warnings’ during installation.

-Meghan


On Apr 2, 2015, at 10:21 AM, vcloitre <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes I had HDF5 test failures indeed.

**Comment by deniadjokic** [comment]
Trying it now. @mbmcgarry, elaborating on how to install coin-cbc and hdf5 from source might be useful here. The linked urls are not super clear on how to do this. And if there is no hdf5 build for Mac as of now, should we just be following the unix environment instructions?

**Comment by mbmcgarry** [comment]
Updated the instructions for building HDF5 and Coin from source. @deniadjokic or @vcloitre , can you check it out again when you get a chance?

**Comment by vcloitre** [comment]
Just a detail : concerning HDF5, when I go to http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.13/src/hdf5-1.8.13.tar.gz, the downloaded file ends with .tar file instead of a .tar.gz file. We may thus need to replace line 189 with : mv hdf5-1.8.13.tar hdf5/

**Comment by mbmcgarry** [comment]
Weird - when I click on the link below, it displays a .tar.gz file (though there is also an alternative .tar file available from this page: http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.13/src/ )

Does anyone else see the link from the webpage as being a .tar ?

-Meghan


On Apr 7, 2015, at 4:19 PM, vcloitre <notifications@github.com<mailto:notifications@github.com>> wrote:


Just a detail : concerning HDF5, when I go to http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.13/src/hdf5-1.8.13.tar.gz, the downloaded file ends with .tar file instead of a .tar.gz file. We may thus need to replace line 189 with : mv hdf5-1.8.13.tar hdf5/

**Comment by deniadjokic** [comment]
Mine downloads as a .tar.gz file...

---
Denia Djokic
Postdoctoral Researcher
UC Berkeley Nuclear Engineering

**Comment by mbmcgarry** [comment]
Maybe @vcloitre 's .gz extension was just hidden?  In any case, I'm pinging this for consideration again.

**Comment by vcloitre** [comment]
@mbmcgarry my file's extension while downloading is .tar.gz.download but oddly it automatically becomes .tar right after the download is complete.
Then the command "mv hdf5-1.8.13.tar.gz hdf5/" gives rise to an error (I have to write "mv hdf5-1.8.13.tar hdf5/")

**Comment by mbmcgarry** [comment]
Hi Vincent,
It sounds like Safari is automatically unzipping the file on download. I’ll adjust the notes to mention this, but also you can turn it off if you’d like by following these instructions<https://wiki.umbc.edu/pages/viewpage.action?pageId=31919091>.

-Meghan


On Apr 9, 2015, at 5:16 PM, vcloitre <notifications@github.com<mailto:notifications@github.com>> wrote:


@mbmcgarry<https://github.com/mbmcgarry> my file's extension while downloading is .tar.gz.download but oddly it automatically becomes .tar right after the download is complete.
Then the command "mv hdf5-1.8.13.tar.gz hdf5/" gives rise to an error (I have to write "mv hdf5-1.8.13.tar hdf5/")

**Comment by vcloitre** [comment]
Thanks Meghan now I have a .tar.gz file indeed :)

**Comment by mbmcgarry** [comment]
Ping

**Comment by gidden** [comment]
thanks @mbmcgarry and @vcloitre and @deniadjokic for reviewing

**Pull request merged**
