### PR TITLE
mocksim can now take custom lifetimes for tested agents.

### PR DESCRIPTION
**Pull request by rwcarlsen**
allows testing of end-of-life behavior of agents.

### CODE REVIEW

**Comment by gidden** [comment]
can you add a test for this behavior, please?

**Comment by gidden** [comment]
and/or show a test that uses it?

**Comment by gidden** [comment]
@rwcarlsen, please let me know if you can get to this for 1.3

**Comment by rwcarlsen** [comment]
nope.  to 1.4.

**Comment by rwcarlsen** [comment]
added a test.

**Comment by rwcarlsen** [comment]
Please note that this should be merged into the release branch even though the PR is for into develop (it has been around for a while).  I'd rather not close and reopen - it keeps our issues/history cleaner on github.

**Comment by rwcarlsen** [comment]
Should have been merged into release :)

**Comment by mbmcgarry** [comment]
Manually merged into v1.3.0-release: 5ecfc06..5773a3f
Thanks @rwcarlsen

**Comment by mbmcgarry** [comment]
I couldn't see a way to change the branch I was merging into, so I did the manual merge that we've been doing to sync develop with r1.3.0-release. If this was the wrong way to do it then I can revert.

**Comment by gidden** [comment]
So v1.3.0-release now has an extra merge commit in it. I'm not sure what
the best way way forward is here. I *think* that can be ignored and we can
move on.

For future posterity, the ideal workflow here would have been:
```
git checkout v1.3.0-release
git merge --no-ff rwcarlsen/branch-name
git push upstream v1.3.0-release
git checkout develop
git merge --no-ff v1.3.0-release
git push upstream develop
```

On Thu, May 21, 2015 at 3:53 PM, mbmcgarry <notifications@github.com> wrote:

> I couldn't see a way to change the branch I was merging into, so I did the
> manual merge that we've been doing to sync develop with r1.3.0-release. If
> this was the wrong way to do it then I can revert.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus/pull/1123#issuecomment-104417403>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by gidden** [comment]
(all being done manually)

On Thu, May 21, 2015 at 3:57 PM, Matthew Gidden <gidden@wisc.edu> wrote:

> So v1.3.0-release now has an extra merge commit in it. I'm not sure what
> the best way way forward is here. I *think* that can be ignored and we can
> move on.
>
> For future posterity, the ideal workflow here would have been:
> ```
> git checkout v1.3.0-release
> git merge --no-ff rwcarlsen/branch-name
> git push upstream v1.3.0-release
> git checkout develop
> git merge --no-ff v1.3.0-release
> git push upstream develop
> ```
>
> On Thu, May 21, 2015 at 3:53 PM, mbmcgarry <notifications@github.com>
> wrote:
>
>> I couldn't see a way to change the branch I was merging into, so I did
>> the manual merge that we've been doing to sync develop with r1.3.0-release.
>> If this was the wrong way to do it then I can revert.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cyclus/cyclus/pull/1123#issuecomment-104417403>.
>>
>
>
>
> --
> Matthew Gidden, Ph.D.
> Postdoctoral Associate, Nuclear Engineering
> The University of Wisconsin -- Madison
> Ph. 225.892.3192
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by mbmcgarry** [comment]
Ahh, that makes sense. Thanks, and sorry for causing confusion.

-Meghan


On May 21, 2015, at 3:57 PM, Matthew Gidden <notifications@github.com<mailto:notifications@github.com>> wrote:

So v1.3.0-release now has an extra merge commit in it. I'm not sure what
the best way way forward is here. I *think* that can be ignored and we can
move on.

For future posterity, the ideal workflow here would have been:
```
git checkout v1.3.0-release
git merge --no-ff rwcarlsen/branch-name
git push upstream v1.3.0-release
git checkout develop
git merge --no-ff v1.3.0-release
git push upstream develop
```

On Thu, May 21, 2015 at 3:53 PM, mbmcgarry <notifications@github.com<mailto:notifications@github.com>> wrote:

> I couldn't see a way to change the branch I was merging into, so I did the
> manual merge that we've been doing to sync develop with r1.3.0-release. If
> this was the wrong way to do it then I can revert.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus/pull/1123#issuecomment-104417403>.
>



--
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

—
Reply to this email directly or view it on GitHub<https://github.com/cyclus/cyclus/pull/1123#issuecomment-104418225>.

*************************************************************************
Meghan McGarry, PhD ~ http://mbmcgarry.github.io/
Postdoctoral Fellow, Consortium for Verification Technology
Computational Nuclear Engineering ~ http://cnerg.engr.wisc.edu
Engineering Physics ~ UW-Madison ~ 608-263-6974
*************************************************************************

**Pull request merged**
