### PR TITLE
updates readme to indicate continuous integration

### PR DESCRIPTION
**Pull request by samgdotson**
This PR updates the README and will allow @abachma2 to check CircleCI.

### CODE REVIEW

**Comment by abachma2** [comment]
This PR is for @bam241 and I to see if the login info for the DockerHub image is passed when someone outside the Cyclus organization makes a PR. It looks like this information is passed during the ``deploy_latest`` and ``deploy_stable`` jobs of the ``circle.yml`` file. But it look like those jobs are done on the merge part, not on the PR itself.

**Comment by bam241** [comment]
thx a lot @samgdotson 
my conclusion from this test are:
dockerhub context are not passed to this, so probably limited to cyclus gihtub team
variable in the cyclus/CI config are passed as the Cycamore and Cymetric token is running.

this might be of interest for you @gonuke (as it is the opposite of all the implementation we did for CNERG circle...)

**Comment by gonuke** [comment]
Thanks for this little addition @samgdotson. Hopefully soon, we'll have all CI moved over to GitHub Actions and we can ping you to update this accordingly (or withdraw it).

**Comment by gonuke** [comment]
This guidance has been superseded by changes in our CI to use github actions instead of CircleCI.  Please update the PR to indicate this, or close/withdraw it.

**Comment by abachma2** [comment]
I don't think this PR is no longer needed, since the CI has been moved over the GitHub Actions. I am closing it.

**Pull request closed without merging**
