### PR TITLE
More Python Wrapping.

### PR DESCRIPTION
**Pull request by scopatz**
Some minor bits I missed before. @FlanFlanagan @bam241 @hodger

### CODE REVIEW

**Comment by scopatz** [comment]
I think this is ready to go in if there are no objections.

**Comment by scopatz** [comment]
Ping!

**Comment by hodger** [comment]
The changes look good to me

**Comment by scopatz** [comment]
Feel free to merge then @hodger.

**Comment by hodger** [comment]
Thanks @scopatz!

**Pull request merged**
