### PR TITLE
Recipe improvements

### PR DESCRIPTION
**Pull request by scopatz**
Here are some needed conda recipe improvements.  These allow me to build cycamore locally based off a linking to the conda package libs.  Relevant cyclus commands (such as `cyclus -a`) seem to work.

### CODE REVIEW

**Comment by gonuke** [comment]
Adding [this link] (https://groups.google.com/d/msg/cyclus-users/LF7waa5wuGg/mBf96ReUCwAJ) for context

**Comment by gonuke** [comment]
If I am reading your email thread correctly - does this require a certain min version of Conda?

**Comment by scopatz** [comment]
I have added some explanatory comments in this script.

**Comment by scopatz** [comment]
Ok, you can now download the cyclus conda package that is produced by this recipe [here](https://drive.google.com/file/d/0BxUpd34yizZrQnNHYlZfS3NiRkk/view?usp=sharing) You can download and install this via the command

```console
$ conda install /path/to/package
```

On a completely fresh system, using this cyclus package, you can then install the `develop` version of cycamore. Previous versions (v1.3.x) fail for some reason related to cmake not being able to FindCyclus fully.  This seems to have been fixed though.

Once this is merged, I'll put in a corresponding PR for cycamore.

**Comment by gonuke** [comment]
Hmmm.... this may be a user error, but I can't run unit tests on a clean Ubuntu 15 system with only cyclus-deps and this updated package.

Needed to apt-get: gfortran, libtcmalloc-minimal4 and now can't find gtest

do we package gtest with cyclus on conda?

**Comment by scopatz** [comment]
Can you run cyclus itself, though?

**Comment by gonuke** [comment]
I was able to run cyclus!  (after some of the apt-getting)

**Comment by scopatz** [comment]
Ahh the tcmalloc thing should be optional, but I probably had it on my system. Why did you need gfortran, though? Where does that come in?

**Comment by scopatz** [comment]
Oh maybe from BLAS/LAPACK.

**Comment by gonuke** [comment]
I know - but I can't build cycamore from source on a clean system with just this package.  I'm trying some other things right now

**Comment by gonuke** [comment]
Here's what I did:
* loaded a clean Ubuntu 15.10
* apt-get'ed all the cyclus dependencies per the README
* cloned and installed cyclus and cycamore from source successfully in .local (failed on HDF5, that's a different issue)
* deleted .local and all repo clones
* installed miniconda in ~/miniconda
* conda install'ed cyclus-deps
* installed your custom conda tarball
* cloned cycamore
* build against prefix & cyclus_root in ~/miniconda
* failed as logged in https://gist.github.com/gonuke/46409ddbff8627363ee0

**Comment by scopatz** [comment]
What cycamore branch are you trying to build?

**Comment by rwcarlsen** [comment]
Somewhat tangential - but the cyclus/cycamore image on dockerhub contains
the latest passing develop build of cyclus+cycamore always.  Could be
another potentially useful starting point for new users/developers.

**Comment by gonuke** [comment]
I'm trying to build cycamore `develop`

**Comment by gonuke** [comment]
Do I need to turn on C++-11 when I build cycamore?  It looks like it's on for the cyclus build

**Comment by gonuke** [comment]
Or vice versa?  I'm baffled as to why it's not able to resolve all the references at link time

**Comment by gonuke** [comment]
Trying again on Ubuntu 14.04

**Comment by gonuke** [comment]
Progress (???)

On a Ubuntu 14 machine, I did the following:
    1  apt-get install -y cmake make libboost-all-dev libxml2-dev libxml++2.6-dev libsqlite3-dev libhdf5-serial-dev libbz2-dev coinor-libcbc-dev coinor-libcoinutils-dev coinor-libosi-dev coinor-libclp-dev coinor-libcgl-dev libblas-dev liblapack-dev g++ libgoogle-perftools-dev git
    2  wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    3  bash Miniconda3-latest-Linux-x86_64.sh -b -p ~/miniconda
    4  export PATH="${HOME}/miniconda/bin:${PATH}"
    5  curl -L http://fuelcycle.org/_downloads/condarc >> ~/.condarc
    6  conda install cyclus-deps
    7  conda install cyclus-0.0-nightly.tar.bz2
    8  cyclus
    9  git clone https://github.com/cyclus/cycamore.git
   10  cd cycamore/
   11  python install.py --prefix=${HOME}/miniconda --cyclus_root=${HOME}/miniconda |& tee ~/cycamore.build.log

And it only complained about missing liblzma references, so I apt-getted liblzma-dev and was able to manually link cycamore_unit_tests by adding a reference to lzma.

but... it segfaults when I try to run it  :(

**Comment by scopatz** [comment]
OK I have discovered at least one problem.  When trying to run cyclus tests you (not even cycamore's) you see:

```console
scopatz@localhost ~ $ which cyclus_unit_tests
/home/scopatz/miniconda/bin/cyclus_unit_tests
scopatz@localhost ~ $ cyclus_unit_tests
/home/scopatz/miniconda/bin/cyclus_unit_tests_base: error while loading shared libraries: libbaseagentunittests.so: cannot open shared object file: No such file or directory
scopatz@localhost ~ $ ldd $(which cyclus_unit_tests_base) | grep "not found"
	libbaseagentunittests.so => not found
	libgtest.so => not found
scopatz@localhost ~ $ ls ~/miniconda/lib/cyclus 
libagents.so  libbaseagentunittests.so  libgtest.so  tests
```

So we install libgtest and libbaseagentunittests into a non-standard location (`lib/cyclus` rather thna just `lib`).  I'll need to modify the test script to know about this as an absolute fallback.

**Comment by scopatz** [comment]
Though the real fix would be for `cyclus_unit_tests` to use `$CYCLUS_PATH`...

**Comment by scopatz** [comment]
Ok - here is a new conda package with the updated library paths: https://drive.google.com/open?id=0BxUpd34yizZrMUl6dUlEelpIY0k

**Comment by gonuke** [comment]
I can get cycamore to build against this now after fighting through a few issues:

1. the following are missing from a clean Ubuntu 14.04 and also from cyclus-deps:
    * libtcmalloc-minimal4
    * gfortran
    * libglib2.0-dev

2. the COIN pkg in cyclus-deps does not include the COIN BZ2 library:
```
	COIN BZ2: COIN_BZ2_LIBRARY-NOTFOUND
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find COIN (missing: COIN_BZ2_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /root/miniconda/share/cyclus/cmake/FindCOIN.cmake:124 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:120 (FIND_PACKAGE)
```
I'm not sure what the dependency graph for that is, and I can't just apt-get that library.  So I apt-get all the COIN dependencies listed on the Cyclus readme.  That didn't help.

I then apt-get libbz2-dev

3. Then it builds successfully.

4. cycamore_unit_tests fails with bad path to nuc_data: it's hard-wired as /home/scopatz/.....
```
export CYCLUS_NUC_DATA=${HOME}/miniconda/share/cyclus
```
5. tests now run to completion with 51 failures

**Comment by scopatz** [comment]
> I then apt-get libbz2-dev

Yup, this is needed.  I think that cyclus-deps is way out of date, or perhaps, more correctly not useful for developing cyclus or cyclus archetypes.  I'll PR a different recipe.

> cycamore_unit_tests fails with bad path to nuc_data: it's hard-wired as /home/scopatz/.....

This is a bug (or issue?) in cyclus. Cyclus uses cmake to fill in template C++ file at compile time with what it perceives to be the install location.  Thus cyclus itself is not super redistributable.  We get around this in conda by creating a wrapper script with the correct install location. 

I think that it is this way because no one wanted to figure out how to have a shared object locate itself from within C++.  It is not much easier with Bash, as I recall, so a wrapper script wouldn't be super helpful unless we went to xonsh :)

For the time being, folks that want to develop archetypes off of the cyclus conda package should probably just set the environment variable.

**Comment by gonuke** [comment]
There is still some path hardcoding in there:
```
root@cyclus-clean-build:~# cyclus -p
:/root/.local/lib/cyclus:/root/miniconda/lib/cyclus:/home/scopatz/miniconda/envs/_build/lib/cyclus:/home/scopatz/miniconda/conda-bld/work/cyclus-develop/build/lib/cyclus
```
This causes test failures for cyclus (IntegTests* & DiscoveryTests*), e.g.

```
[ RUN      ] IntegTests.RunAllInfiles
unknown file: Failure
C++ exception with description "custom_dt.xml not found in /home/scopatz/miniconda/envs/_build/share/cyclus/input/ or /home/scopatz/miniconda/conda-bld/work/cyclus-develop/build/share/cyclus/input/" thrown in the test body.
[  FAILED  ] IntegTests.RunAllInfiles (7 ms)
[ RUN      ] IntegTests.CustomTimestepDur
unknown file: Failure
C++ exception with description "custom_dt.xml not found in /home/scopatz/miniconda/envs/_build/share/cyclus/input/ or /home/scopatz/miniconda/conda-bld/work/cyclus-develop/build/share/cyclus/input/" thrown in the test body.
[  FAILED  ] IntegTests.CustomTimestepDur (4 ms)
```

When I set the CYCLUS_NUC_DATA correctly, I get more failures:
[  FAILED  ] 18 tests, listed below:
[  FAILED  ] MatQueryTests.MassAndMoles
[  FAILED  ] MaterialMatQueryTest.ExtractDiffComp
[  FAILED  ] EnrichmentTests.material
[  FAILED  ] EnrichmentTests.enrichmentcalcs
[  FAILED  ] DecayTests.simple
[  FAILED  ] IntegTests.RunAllInfiles
[  FAILED  ] IntegTests.CustomTimestepDur
[  FAILED  ] DiscoveryTests.DiscoverSpec
[  FAILED  ] DiscoveryTests.DiscoverSpecsInInstallPath
[  FAILED  ] CompositionTests.create_atom
[  FAILED  ] CompositionTests.create_mass
[  FAILED  ] CompositionTests.decay
[  FAILED  ] MaterialTest.DecayManual
[  FAILED  ] MaterialTest.DecayLazy
[  FAILED  ] MaterialTest.DecayShortcut
[  FAILED  ] MaterialTest.DecayCustomTimeStep
[  FAILED  ] MaterialTest.ExtractPrevDecay
[  FAILED  ] MaterialTest.AbsorbPrevDecay

(oddly, they pass otherwise...?)

**Comment by scopatz** [comment]
> There is still some path hardcoding in there:

Yes, this is the same templating issue.  I believe that all of the cyclus environment variables are templated to the user's install path at compile time.  When you run cyclus from the conda package, you are getting the wrapped script version that rewrites these variables for you.  When you look at a unit test execuable custom compiled based on a relocated cyclus, you have to manually set these variables.

Looking at the wrapper script, it seems like these variables are `$CYCLUS_PATH`, `$CYCLUS_NUC_DATA`, and `$CYCLUS_RNG_SCHEMA`

**Comment by scopatz** [comment]
An alternative, of course, is to have a tests script that relies on `which cyclus`.  This is probably a good idea in general.

**Comment by rwcarlsen** [comment]
On Thu, Nov 19, 2015 at 5:12 PM, Anthony Scopatz <notifications@github.com>
wrote:

> I then apt-get libbz2-dev
>
> Yup, this is needed. I think that cyclus-deps is way out of date, or
> perhaps, more correctly not useful for developing cyclus or cyclus
> archetypes. I'll PR a different recipe.
>
> cycamore_unit_tests fails with bad path to nuc_data: it's hard-wired as
> /home/scopatz/.....
>
> This is a bug (or issue?) in cyclus. Cyclus uses cmake to fill in template
> C++ file at compile time with what it perceives to be the install location.
> Thus cyclus itself is not super redistributable. We get around this in
> conda by creating a wrapper script with the correct install location.
>
This is a bit disingenuous.  Cyclus checks the CYCLUS_NUC_DATA (or
something similar) env var, it checks the install location, it checks the
build location, etc.  when trying to find the nuc data - it doesn't just
blindly use a hard-coded path.  It could certainly be improved though :-)


> I think that it is this way because no one wanted to figure out how to
> have a shared object locate itself from within C++. It is not much easier
> with Bash, as I recall, so a wrapper script wouldn't be super helpful
> unless we went to xonsh :)
>
Seems drastic :)

> For the time being, folks that want to develop archetypes off of the
> cyclus conda package should probably just set the environment variable.
>
Seems reasonable.

**Comment by gonuke** [comment]
@scopatz - I saw somewhere (but can't find it now) that you made a cyclus-dev-deps package, or similar.  Perhaps it would help me to be clear on what experience you expect the developer to have, vis-a-vis installing dependencies and setting environment variables, and I can ensure that it meets those expectations.  I have a general idea, but there is no use in me posting errors for things that are just known limitations.

**Comment by scopatz** [comment]
Here is what I would expect / hope to work:

1. user installs cyclus package.
2. User decides to become archetype developer. This requires getting additional packages (such as compilers and headers) from somewhere (cyclus-dev-deps or their system).
3. cycamore and cycstub-based packages that are compiled locally are able to link against and be run with the conda cyclus package.  The archetype developer need not also be a kernel developer.
4. the archetype unit test files should run, but the archetype may need to point `$LD_LIBRARY_PATH` to `~/miniconda/lib/cyclus` or similar and also the cyclus-specific envrionment variables.  However, this should not be needed just to run cyclus with the custom archetypes.

I believe that this PR does all of those things in its present state.  There are ways that this could be streamlined and made easier (no library path setting, no setting cyclus environment variables to run tests). However that requires modifications to cyclus Env.cc and Env.h (right but difficult) or creating a test wrapper script as a part of cycamore and cycstub (easy but another layer to maintain).

Hope this helps.

**Comment by gonuke** [comment]
I think I got it to work - other than path issues!!! 

Did this on a clear Ubuntu 14.10

```
apt-get install -y libtcmalloc-minimal4 gfortran

wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh; bash Miniconda3-latest-Linux-x86_64.sh -b -p ~/miniconda

export PATH="${HOME}/miniconda/bin:${PATH}"; export LD_LIBRARY_PATH="${HOME}/miniconda/lib"

curl -L http://fuelcycle.org/_downloads/condarc >> ~/.condarc; conda install cyclus-deps

conda install cyclus-0.0-nightly.tar.bz2; cyclus; cyclus_unit_tests

export CYCLUS_NUC_DATA=${HOME}/miniconda/share/cyclus/cyclus_nuc_data.h5

apt-get install -y cmake make libboost-all-dev libxml2-dev libxml++2.6-dev libsqlite3-dev libhdf5-serial-dev libbz2-dev coinor-libcbc-dev coinor-libcoinutils-dev coinor-libosi-dev coinor-libclp-dev coinor-libcgl-dev libblas-dev liblapack-dev g++ libgoogle-perftools-dev git libglib2.0-dev

git clone https://github.com/cyclus/cycamore.git; cd cycamore

python install.py --cmake_prefix_path=${HOME}/miniconda --prefix=${HOME}/miniconda --cyclus_root=${HOME}/miniconda |& tee ~/cycamore.build.log
```

**Comment by gonuke** [comment]
Note: there are path issues with cycamore in that it can't find the installed modules.  I had to link them into my current dir to get it to work

**Comment by gonuke** [comment]
I've retested and got nearly everything to work if I set CYCLUS_PATH correctly.

The only things that don't work are cyclus tests that look for the test input and can't find it.  This is because those tests live in .../share/cyclus and we don't have way to point to that whole directory - only to individual files that are there: NUC_DATA and RNG_SCHEMA

I see two ways to fix this:
1. add an env variable for CYLCUS_SHARE_PATH (or similar) that points to the directory
2. add an env variable that's only for the tests that points to the directory of input files

**Comment by gonuke** [comment]
I'm going to merge this now given my general success and because this PR meets its purpose.

**Comment by gonuke** [comment]
Thanks @scopatz

**Comment by scopatz** [comment]
Thanks @gonuke!

**Pull request merged**
