### PR TITLE
removed test_abi.py

### PR DESCRIPTION
**Pull request by gidden**
per https://groups.google.com/forum/#!topic/cyclus-dev/mI0EnE99L8Q

### CODE REVIEW

**Comment by scopatz** [comment]
Let's keep this conversation on the mailing list.

**Comment by gidden** [comment]
Agreed, just offering a PR to be merged/closed upon resolution

On Tue, Feb 17, 2015 at 4:42 PM, Anthony Scopatz <notifications@github.com>
wrote:

> Let's keep this conversation on the mailing list.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus/pull/1086#issuecomment-74771112>.
>



-- 
Matthew Gidden
Ph.D. Candidate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by scopatz** [comment]
Ok :)

**Comment by gidden** [comment]
closing in favor of #1099

**Pull request closed without merging**
