### PR TITLE
Cbc 2.9.x interface, prevents segfault

### PR DESCRIPTION
**Pull request by scopatz**
Updating the OsiCbc interface to the latest version prevents segfaults in the unit tests on my laptop.  This took me months (off and on) to figure out.

### CODE REVIEW

**Comment by scopatz** [comment]
Can this get a review please? @FlanFlanagan?

**Comment by gonuke** [comment]
@gidden might also want to take a look

**Comment by gidden** [comment]
Hi everyone. Seems like some very innocuous changes, sorry they caused such a headache @scopatz. I've added a PR to this branch testing the 2.9 files with cbc 2.8 in scopatz/cyclus#2. Tests pass for me. I've also included a warning for the future.

**Comment by gidden** [comment]
Looks good to me. @scopatz and I had a discussion in scopatz/cyclus#2 that our build should probably fail if > 2.9 is encountered.

**Comment by scopatz** [comment]
Thanks for looking at this @gidden. It doesn't seem like Coin version information is actually available to CMake, though, when I went to try to implement it.  Would you be OK with an `#error` directive in light of that?

**Comment by gidden** [comment]
Seems reasonable to me. Don't want to have people go searching for months
after this again =)

**Comment by scopatz** [comment]
OK great! I have implemented that and tested it locally.

**Comment by gidden** [comment]
lgtm, thanks @scopatz, happy to be reviewing again =)

**Pull request merged**
