### PR TITLE
Ui

### PR DESCRIPTION
**Pull request by gidden**
Adds structure to uilabel and doc annotation values to match alias.

This needs to be confirmed by @FlanFlanagan

### CODE REVIEW

**Comment by gidden** [comment]
hold on this

**Comment by gonuke** [comment]
Is this ready for a review?

**Comment by gidden** [comment]
Yes, it can be reviewed by anyone, but needs to be checked at minimum by
@flanflanagan

On Sat, May 16, 2015 at 10:36 PM, Paul Wilson <notifications@github.com>
wrote:

> Is this ready for a review?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus/pull/1162#issuecomment-102732738>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by FlanFlanagan** [comment]
I will give this a try today. I'll need to update my cyclus to this branch
correct?

On Sun, May 17, 2015 at 10:47 AM, Matthew Gidden <notifications@github.com>
wrote:

> Yes, it can be reviewed by anyone, but needs to be checked at minimum by
> @flanflanagan
>
> On Sat, May 16, 2015 at 10:36 PM, Paul Wilson <notifications@github.com>
> wrote:
>
> > Is this ready for a review?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cyclus/cyclus/pull/1162#issuecomment-102732738>.
> >
>
>
>
> --
> Matthew Gidden, Ph.D.
> Postdoctoral Associate, Nuclear Engineering
> The University of Wisconsin -- Madison
> Ph. 225.892.3192
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus/pull/1162#issuecomment-102816142>.
>



-- 
Robert Flanagan
Graduate Research Assistant
Nuclear and Radiation Engineering Program
Department of Mechanical Engineering
The University of Texas at Austin

**Comment by gidden** [comment]
yup, you'll need the changes on this branch

On Mon, May 18, 2015 at 10:31 AM, FlanFlanagan <notifications@github.com>
wrote:

> I will give this a try today. I'll need to update my cyclus to this branch
> correct?
>
> On Sun, May 17, 2015 at 10:47 AM, Matthew Gidden <notifications@github.com
> >
> wrote:
>
> > Yes, it can be reviewed by anyone, but needs to be checked at minimum by
> > @flanflanagan
> >
> > On Sat, May 16, 2015 at 10:36 PM, Paul Wilson <notifications@github.com>
> > wrote:
> >
> > > Is this ready for a review?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/cyclus/cyclus/pull/1162#issuecomment-102732738>.
> > >
> >
> >
> >
> > --
> > Matthew Gidden, Ph.D.
> > Postdoctoral Associate, Nuclear Engineering
> > The University of Wisconsin -- Madison
> > Ph. 225.892.3192
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cyclus/cyclus/pull/1162#issuecomment-102816142>.
> >
>
>
>
> --
> Robert Flanagan
> Graduate Research Assistant
> Nuclear and Radiation Engineering Program
> Department of Mechanical Engineering
> The University of Texas at Austin
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus/pull/1162#issuecomment-103105406>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by gidden** [comment]
@FlanFlanagan, does your cyclist2 updates require this branch be merged (and if so, would you like to do the honors?

**Comment by FlanFlanagan** [comment]
Er, I'm actually not sure if it does or not, but it does work with this
branch. So I will go ahead and merge it.

On Mon, May 18, 2015 at 3:40 PM, Matthew Gidden <notifications@github.com>
wrote:

> @FlanFlanagan <https://github.com/FlanFlanagan>, does your cyclist2
> updates require this branch be merged (and if so, would you like to do the
> honors?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus/pull/1162#issuecomment-103204246>.
>



-- 
Robert Flanagan
Graduate Research Assistant
Nuclear and Radiation Engineering Program
Department of Mechanical Engineering
The University of Texas at Austin

**Pull request merged**
