### PR TITLE
Vechotfix

### PR DESCRIPTION
**Pull request by gidden**
these containers were picking up full subaliases for complex containers

### CODE REVIEW

**Comment by gonuke** [comment]
Is there a test that fails prior to these changes that we can include in our test suite?

**Comment by gidden** [comment]
Hi Paul,

I could try to replicate the container I'm proposing to use in the
GrowthRegion, though I think the better thing to do (in the future) is to
enumerate more test cases in the infiletodb test.

On Sat, May 16, 2015 at 11:06 PM, Paul Wilson <notifications@github.com>
wrote:

> Is there a test that fails prior to these changes that we can include in
> our test suite?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus/pull/1168#issuecomment-102736553>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by rwcarlsen** [comment]
I would really like to see a test.  It should be pretty quick to write.

**Comment by gidden** [comment]
test added. you can test it on current develop head to see that it fails there. this now needs to be coordinated with #1165 since it uses pairs as well.

**Comment by gidden** [comment]
again, I think some sort of refactor would be nice to make these test cases easier to enumerate

**Comment by rwcarlsen** [comment]
So I just merged this, but then realized it is PR'd into develop :-/ Oh well.  Merged.

**Comment by gidden** [comment]
We should probably revert the merge and merge it into the release branch.

On Mon, May 18, 2015 at 11:45 AM, Robert Carlsen <notifications@github.com>
wrote:

> So I just merged this, but then realized it is PR'd into develop :-/ Oh
> well. Merged.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus/pull/1168#issuecomment-103123233>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by rwcarlsen** [comment]
I merged it into the release branch.  The PR was just for the wrong branch.

**Comment by gidden** [comment]
Can we cleanly merge release into develop right now?

On Mon, May 18, 2015 at 12:04 PM, Robert Carlsen <notifications@github.com>
wrote:

> I merged it into the release branch. The PR was just for the wrong branch.
>
> On Mon, May 18, 2015 at 11:01 AM, Matthew Gidden <notifications@github.com
> >
> wrote:
>
> > We should probably revert the merge and merge it into the release branch.
> >
> > On Mon, May 18, 2015 at 11:45 AM, Robert Carlsen <
> notifications@github.com
> > >
> > wrote:
> >
> > > So I just merged this, but then realized it is PR'd into develop :-/ Oh
> > > well. Merged.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/cyclus/cyclus/pull/1168#issuecomment-103123233>.
> > >
> >
> >
> >
> > --
> > Matthew Gidden, Ph.D.
> > Postdoctoral Associate, Nuclear Engineering
> > The University of Wisconsin -- Madison
> > Ph. 225.892.3192
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cyclus/cyclus/pull/1168#issuecomment-103130045>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus/pull/1168#issuecomment-103131920>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by rwcarlsen** [comment]
release merged into develop.

**Comment by gidden** [comment]
develop currently looks like it's failing on the test this PR added. I'm not sure what's up @rwcarlsen, would you mind looking into it?

**Pull request closed without merging**
