### PR TITLE
hotfix for pairs of pairs

### PR DESCRIPTION
**Pull request by gidden**
first and second names get overloaded when pairs are inside of other pairs

### CODE REVIEW

**Comment by mbmcgarry** [comment]
Looks good to me but is a bit outside my experience.  I'll merge it this evening if no one comments in the meantime.

**Comment by gonuke** [comment]
This looks good @gidden.  Is this the same issue as fixed in #1120? but now for pairs?

**Comment by gidden** [comment]
effectively, yes

On Sat, May 16, 2015 at 10:55 PM, Paul Wilson <notifications@github.com>
wrote:

> This looks good @gidden <https://github.com/gidden>. Is this the same
> issue as fixed in #1120 <https://github.com/cyclus/cyclus/pull/1120>? but
> now for pairs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus/pull/1165#issuecomment-102733586>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by rwcarlsen** [comment]
SchemaFilter for pairs also needs to be updated or this won't work.

**Comment by gidden** [comment]
this doesn't touch the schema

**Comment by gidden** [comment]
only the variable names in the infiletodb filter

**Comment by rwcarlsen** [comment]
Quite right!  Looks good to me.

**Comment by gidden** [comment]
I hear three looks good, would someone mind merging, please?

**Comment by gidden** [comment]
(and thank you!)

**Pull request merged**
