### PR TITLE
Pywrap

### PR DESCRIPTION
**Pull request by scopatz**
Some more Python wrapping. @FlanFlanagan and others!

### CODE REVIEW

**Comment by scopatz** [comment]
OK, this is now able to fully drive a cyclus simulation through Python.  You an test it out with, 

```console
$ python -m cyclus /path/to/input/file
```

**Comment by Baaaaam** [comment]
it worked from cyclus folder:
```
$> pwd
 /Users/mouginot/work/app/cyclus/cyclus
$> python cyclus ~/work/cyclus_play/input.xml
```
but I got an error from an other repo:
```
$> pwd 
~/work/cyclus_play
$> python cyclus input.xml                                                                                                                                        
/opt/local/Library/Frameworks/Python.framework/Versions/3.5/Resources/Python.app/Contents/MacOS/Python: can't open file 'cyclus': [Errno 2] No such file or directory
```

**Comment by scopatz** [comment]
Hi @Baaaaam, you need to have the `-m` before the `cyclus` on the command line. Thanks for trying it out!

**Comment by Baaaaam** [comment]
@scopatz works perfectly with the `-m` (sorry about it)

I'll let to other the chance to review and merge it in 2 days otherwise.

thx @scopatz this is super cool!
btw is there a way to set the verbose level ?

**Comment by scopatz** [comment]
> I'll let to other the chance to review, I will merge it in 2 days otherwise.

> thx @scopatz this is super cool!

Thanks, sounds good.

> btw is there a way to set the verbose level ?

Yes! You can run any of the normal cyclus command line options. Instead of running `cyclus`, use `python -m cyclus` instead.  So if you wanted to run help, you could run `python -m cyclus -h` to see all of the options.

The only thing I didn't reimplement was restart.  That feature is experimental and I expect it to change in the relatively near future.

**Comment by FlanFlanagan** [comment]
This works for me. I'll wait til the deadline @Baaaaam set to merge.

**Comment by scopatz** [comment]
There is no need to wait, really.

**Pull request merged**
