### PR TITLE
Release merge

### PR DESCRIPTION
**Pull request by Baaaaam**
As I had to resolve some conflict, I prefer to PR those merge in order to be sure everything if correct!

### CODE REVIEW

**Comment by Baaaaam** [comment]
@scopatz @gonuke @FlanFlanagan @mbmcgarry 
could someone take a look and merge if ok ?
this would allows to merge all the release changes into develop.

**Comment by Baaaaam** [comment]
it should be ok, but as I had to manually resolve conflict, I would prefer if someone can take a look...

**Comment by scopatz** [comment]
Hi @Baaaaam, if you are the release manager, you have the authority to push up these changes directly, without needing a PR.

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
