### PR TITLE
adding prettyprint

### PR DESCRIPTION
**Pull request by gidden**
With all these recursive containers and various bugs flying around, this is a nice diagnostic tool.

### CODE REVIEW

**Comment by gidden** [comment]
ping @scopatz @rwcarlsen @mbmcgarry or anyone else

**Comment by gidden** [comment]
rebased, pinging @scopatz @rwcarlsen @mbmcgarry or anyone else, again

**Comment by scopatz** [comment]
I recommend that someone who has had their PRs reveiwed by @gidden recently review this one.

**Comment by gidden** [comment]
moving to 1.4

**Comment by opotowsky** [comment]
@gidden is this updated? If so I can review

**Comment by gidden** [comment]
rebased

**Comment by opotowsky** [comment]
Test case added was a result of an offline discussion on how to test this. Thanks @gidden!

**Pull request merged**
