### PR TITLE
Fix minor compiler errors (macro expansion, duplicate `using`)

### PR DESCRIPTION
**Pull request by dermesser**
for issue #1312 - probably doesn't fix it, but contributes to improvements.

### CODE REVIEW

**Comment by gonuke** [comment]
Thank you @dermesser.  Please add a news update by copying `news/TEMPLATE.rst` to a file with a name that matches your PR's purpose and fill in the appropriate sections. (We should clarify this as a requirement of a PR.)

**Comment by dermesser** [comment]
I took the liberty and also fixed a second one-line issue (a duplicate `using` directive), that triggered compiler errors with at least some GCC versions for me. This way, the added `news` "article" is worth it :)

**Comment by dermesser** [comment]
> (We should clarify this as a requirement of a PR.)

I opened #1561 for this - I hope I understood you correctly :)

**Review by gonuke — APPROVED** [review]
thanks @dermesser - this looks good to em

**Comment by bam241** [comment]
btw we probably want to transpose that change in PyNE, as we changed the `pyne.h`

**Pull request merged**
