### PR TITLE
mock simulation now can reconstruct resources for you

### PR DESCRIPTION
**Pull request by rwcarlsen**

### CODE REVIEW

**Comment by rwcarlsen** [comment]
wait a bit on this.

**Comment by rwcarlsen** [comment]
ready now.

**Comment by rwcarlsen** [comment]
I'd really like to get this in soon if someone has time for a review.  Thanks.

**Comment by gidden** [comment]
@rwcarlsen and I were talking in the office. To summarize: by adding a QBackend to the signature of the load methods, all *required* `SimInit` state is taken away. Thus, there is an argument for also making them static functions.

**Comment by rwcarlsen** [comment]
done.  also - we may want to make LoadComposition public in the future, but no need to yet.

**Comment by gidden** [comment]
So these now cause an ABI test failure for me. However, API stability is maintained. That's fine by me, but I don't want to merge in a PR that breaks a test. Can @scopatz chime in here?

**Comment by rwcarlsen** [comment]
@scopatz - how long is this going to have to wait?

**Comment by scopatz** [comment]
Oh sorry, yeah. We shouldn't merge anything in which breaks a test. So this PR should either fix the test or wait until develop progress such that the test is fixed.

**Comment by rwcarlsen** [comment]
This PR doesn't break a test that wasn't already broken.  Especially very broken with clang.

**Comment by scopatz** [comment]
But this causes a new breakage, so it still introduces an error.

**Comment by rwcarlsen** [comment]
ETA on the fix?

**Comment by scopatz** [comment]
I'd rather discuss that on the mailing list thread if it is not going to happen as part of this PR.

**Comment by rwcarlsen** [comment]
Why would it be a part of this PR? - it has nothing to do with this PR and you were going to do it.

**Comment by scopatz** [comment]
Then why are we talking about it on this PR? And yes I offered to do it.

**Comment by mbmcgarry** [comment]
I've reviewed the code and tested it.
Is this OK to merge now @scopatz ?

**Comment by scopatz** [comment]
I'd personally like to try this on my machine, given all the tsuris about it.  I'll do that now.

**Comment by scopatz** [comment]
This works for me now. +1 to merge

**Pull request merged**
