### PR TITLE
adding dockerhub authentication

### PR DESCRIPTION
**Pull request by stompsjo**
This PR adds Dockerhub authentication as a result of changes to Dockerhub policy.

### CODE REVIEW

**Comment by bam241** [comment]
#gonuke I spotted this `Warning: No authentication provided, using CircleCI credentials for pulls from Docker Hub.` in one of our circleCI run, 

So I am wondering if we actually need to use our own credential....

**Comment by bam241** [comment]
cc @gonuke (used # not @ on my previous post...)

**Comment by gonuke** [comment]
I think this can be withdrawn as we move to GH container registry

**Comment by gonuke** [comment]
Could you please withdraw this PR @stompsjo since we've move to Github actions?

**Comment by stompsjo** [comment]
@gonuke Absolutely!

**Pull request closed without merging**
