### PR TITLE
Cython 0.27 Fixes

### PR DESCRIPTION
**Pull request by scopatz**
This implements fixes for Cython v0.27. @bam241, would you mind trying this out please? CC @FlanFlanagan

### CODE REVIEW

**Comment by FlanFlanagan** [comment]
Branch out of date?

**Comment by scopatz** [comment]
Oh! it is...

**Comment by scopatz** [comment]
updated!

**Comment by bam241** [comment]
thx a lot @scopatz !

**Comment by scopatz** [comment]
Thanks @bam241! I am glad this made it in.

**Pull request merged**
