### PR TITLE
Emptyapi

### PR DESCRIPTION
**Pull request by gidden**
helpful for dev tut

### CODE REVIEW

**Comment by rwcarlsen** [comment]
ResourceBuff is deprecated.  And ResBuf already has an empty function.

**Comment by gidden** [comment]
`ResBuf` is deprecated? The cycamore `Sink` still uses it.

**Comment by gidden** [comment]
I'll open a separate PR. The issue at hand is not that it needs an `empty()` function, rather that the capitalization is not consistent between the `empty()` function and the `Pop()` and `Push()` functions.

**Comment by rwcarlsen** [comment]
Well - ResBuf was meant to replace it as better, faster, and easier to use.  With ResourceBuff, you have to do all sorts of annoying casting.  Some of the functions were made lower case for two reasons:

* they are practically getters
* to be consistent with what is seen in the c++ std lib

**Comment by gidden** [comment]
I don't disagree with using `ResBuff`. The `Sink` should have been updated when it was deprecated; however.

I know that they are practically getters/setters; however, it seems strange that some container-like functions are capitalized and others aren't.

**Comment by gidden** [comment]
Let's move the discussion to #1157

**Pull request closed without merging**
