### PR TITLE
Test

### PR DESCRIPTION
**Pull request by gwenchee**

### CODE REVIEW

**Comment by bam241** [comment]
@gwenchee  I think the problem comes from cymetric, for whatever reason, the last merged PR, broken cymetric nosetests as well

**Comment by gwenchee** [comment]
Okay, thanks baptise. I was wondering why this was happening. What should we do? Should I wait for the cycmetric nose tests to pass before merge #1501

**Comment by FlanFlanagan** [comment]
Is this from the last Cymetric PR or Cyclus PR?

**Comment by bam241** [comment]
in theory the `cymetric` test, are there only for information, meaning that we have something to fix with `cymetric`, so I would say no need to wait... but may be make a issue in the `cymetric` repo about it :)

**Comment by bam241** [comment]
@FlanFlanagan I don't know, it seems that it just appear....

**Pull request closed without merging**
