### PR TITLE
Add units 

### PR DESCRIPTION
**Pull request by bam241**
This adds:
- optional unit when recording Timeserie
- add unit when recording inventory (using the unit embedded in Materials)

### CODE REVIEW

**Comment by bam241** [comment]
@FlanFlanagan I am not sure the change I did are enough on the recordtimeserie side.
I did not touch the PythonListener part because I don't understand it...
Please tell me if I have to do something about this....

**Comment by bam241** [comment]
@FlanFlanagan I also don't know is such change are CEP worthy, what do you think ?

**Comment by bam241** [comment]
thx @katyhuff this should be ready to for a last check :)

**Comment by bam241** [comment]
the error on the cymetric test are expected, as the number of columns in some table changed...

**Comment by gonuke** [comment]
Is there a plan to resolve the Cymetric errors?  I'm OK with merging this with downstream errors, as long as we have a clear plan for changes in those downstream repos to resolve this ASAP.

**Comment by bam241** [comment]
@gonuke those error should be fixed by cyclus/cymetric#154

**Comment by bam241** [comment]
This is missing a news file...

**Comment by bam241** [comment]
@gonuke @katyhuff  this should be ready!

**Comment by gonuke** [comment]
LGTM - thanks @bam241

**Pull request merged**
