### PR TITLE
adds a private new decay function to composition

### PR DESCRIPTION
**Pull request by gidden**
I had a test failure on a fresh Ubuntu install from source complaining about the ABI test.

### CODE REVIEW

**Comment by rwcarlsen** [comment]
One of the primary purposes of having private members is to maintain
flexibility to change them (i.e. implementation) without breaking API.  I
thought we decided to just whitelist false positives like this.

**Comment by gidden** [comment]
you're right, forgot about this. how is this not failing on other systems,
tbw?

**Comment by gidden** [comment]
updated

**Comment by gonuke** [comment]
Can someone remind me when we take a new snapshot of the ABI?  And presumably we then cleanout the blacklist?

**Comment by rwcarlsen** [comment]
@gonuke - probably better make an issue for that - otherwise we'll
certainly forget.

**Comment by gonuke** [comment]
I was accidentally ambiguous with my grammar: can someone tell what me the current policy/practice is for the frequency of updating the ABI snapshot?  Is it documented and, if so, do we also clean out the blacklist on those occasions?

**Comment by rwcarlsen** [comment]
http://fuelcycle.org/cep/cep3.html has some instructions.

**Comment by gonuke** [comment]
I'm ready to merge this after a rebase

**Comment by rwcarlsen** [comment]
Merged.  Thanks @gidden.

**Pull request merged**
