### PR TITLE
Speed

### PR DESCRIPTION
**Pull request by rwcarlsen**
runs ~3x faster on fco-like simulation with recipe based facilities.

### CODE REVIEW

**Comment by rwcarlsen** [comment]
same as #1138

**Comment by gidden** [comment]
I'm seeing the following cycamore errors:
```
[ RUN      ] FuelFabTests.FissConstrained
unknown file: Failure
C++ exception with description "removal quantity 1.0000000000000002 larger than buff quantity 1" thrown in the test body.
[  FAILED  ] FuelFabTests.FissConstrained (18 ms)
[ RUN      ] FuelFabTests.SwapTopup
[       OK ] FuelFabTests.SwapTopup (33 ms)
[ RUN      ] FuelFabTests.SwapTopup_ZeroFill
[       OK ] FuelFabTests.SwapTopup_ZeroFill (32 ms)
[ RUN      ] FuelFabTests.SwapTopup_TopupConstrained
unknown file: Failure
C++ exception with description "removal quantity 1.0000000000000002 larger than buff quantity 1" thrown in the test body.
[  FAILED  ] FuelFabTests.SwapTopup_TopupConstrained (19 ms)
[ RUN      ] FuelFabTests.SwapTopup_FissConstrained
[       OK ] FuelFabTests.SwapTopup_FissConstrained (32 ms)
[----------] 20 tests from FuelFabTests (418 ms total)
```

**Comment by rwcarlsen** [comment]
I saw errors like this when I was debugging the fab yesterday.  If you run
with the fab-fix branch, I'm almost positive these errors are gone.  These
errors were most likely introduced by the faster-buf PR merged in a while
back.  And small perturbations to the compiler's output instructions from
this PR resulted in 1e-17 perturbation on some floating point calcs.  In
any case the fab-fix PR from yesterday includes more robust handling of
this sort of floating point error.

**Comment by gidden** [comment]
Ok, things pass with that branch, merging

**Pull request merged**
