### PR TITLE
better docs for enums and allowing abbreviations and full name for fu…

### PR DESCRIPTION
**Pull request by gidden**
…nction types

### CODE REVIEW

**Comment by gidden** [comment]
ok, this should be ready to be reviewed

**Comment by gidden** [comment]
ping

**Comment by mbmcgarry** [comment]
I'm looking at this now. I got a failure on nosetests, but it came from an initdb command, so I'm checking to see whether it's actually from another PR that was recently merged into v1.3.0-release.

**Comment by mbmcgarry** [comment]
merged into develop: a61e86e..cf069e4
thanks @gidden !

**Pull request merged**
